### ISSUE TITLE
Document ConfigurationContainer, Type, and Member Extension Methods

### ISSUE THREAD

**Issue by fdrobidoux** [ExtendedXmlSerializer/home#189]
I'm really enjoying this library, and I've been using it with not too much effort in my current Windows Forms app I'm making for my self-teachings in VB.NET.

However, it took me a while to realize how this whole thing works; I thought I could just create a `ConfigurationContainer`, include the reference to a static function in each of my models with references to their super-class's static function of the same name (so I can add a `.EnableReferences(p => p.Id)` since all my models inherit from a base model with an `ID` property), and it seemed to go well until I realized that when you do `.ConfigureType()`, you get a `ITypeConfiguration` object out of it; you don't get the `ConfiguratioContainer` back. Which, you know, that makes sense, but it wasn't obvious at first.

And while there are examples in this `README.md` and on the official docs, the individual API features lack any documentation, and that contributed to my confusion.

So are there any plans on adding documentation comments in the interfaces' methods at least? It would help a lot.

Thanks!

**Comment by fdrobidoux** [comment]
Thanks for the quick reply!

I understand your situation, and I can see why you'd want to focus on v3 rather than work on documentation for v2. No pressure, man.

I'll be monitoring the advancements of the project, and I'll keep on using v2 as best I can in the meantime.

Have a good one!

**Comment by Mike-EEE** [comment]
As a note/FWIW, in the meantime until we have proper documentation, we have a tag that can be used to filter documentation-type issues here:

https://github.com/wojtpl2/ExtendedXmlSerializer/issues?q=is%3Aissue+label%3ADocumentation

**Comment by ferzisdis** [comment]
Hi!
How will v3 differ from v2?

**Comment by aredshaw** [comment]
Is this a web API we are talking about? If so, I might be able to help.
Can you give me the following?
* The base path
* Endpoints
* All possible methods and parameters
* An API Key (If required)

**Comment by Mike-EEE** [comment]
Hey @aredshaw thanks for the question and apologies for taking so long to answer it!  I am just now getting back from all the holiday cheer. 😁

So in this case, I believe the ask is to improve or even implement documentation around the public-facing API for the `ConfigurationContainer` and associated components.  I believe this would involve doing XML documentation (which I am not a fan of, hence my own personal aversion to this) and ensuring that when a developer pulls in ExtendedXmlSerializer from nuget, and they start to implement features, they see documentation provided in their intellisense so they don't have to go into github here to see what means what.

I am open to other forms of documentation outside of XML, of course.  My primary issue with the XML is that it is baked right into the code file, which adds overhead and makes it difficult to get to the actual code when it matters.

That is my take on this issue.  If anyone else has other thoughts please feel free to add them as well.

**Comment by Mike-EEE** [comment]
Alrighty... going to see if I can take a stab at this issue, finally.  I am simplifying this issue to focus on the `ConfigurationContianer` extension methods.  You know it's bad when the author of said methods uses them a year later only to result in confusion and perplexity. 😆

**Comment by Mike-EEE** [comment]
WHEW!  What a project!  That took a _lot_ of work, but I gotta tell you, it's worth it.  I guess that's part of the draw with documentation: it's quite literally a second effort on the already Herculean effort involved in writing code.

In any case, all the major extension methods have been identified and organized into the main root namespace now courtesy of #274.  That will clear up a lot of unnecessary `using` statements in code.

On top of that, all the methods have been documented.  Well, all the major v2 ones, at least.  There are a few v1 methods that I didn't have much to do with, and I am not sure how much they are used, but everything is accounted for... I am guessing in the ballpark of 150 extension methods. 😱 

I've been taking a few notes and some further work in the wiki to flesh out the documentation even more.  However, all the documentation for the code is in there, and ready to be reviewed if you so fancy.  I'm sure there's a few typos in there, so don't be afraid to point them out or even better, send a PR. 😁

You can check these out in our new preview feed here:

https://ci.appveyor.com/nuget/extendedxmlserializer-preview

Please be sure to select Browse and enable `Include prerelease` in NuGet explorer:

![](https://i.imgur.com/lpZeYIy.png)

PS: I also wanted to say that the v3 that I mentioned earlier has been shelved.  Or at least, how I originally planned it.  It was far too ambitious and its vision was far too involved.  However, getting back into the swing of things here with the documentation, it's tempting to simply do a v3 XML serializer and try not to be everything to everyone (including JSON support, for instance, etc)... something to mull going forward. 🤔🤓

(Of course, now that I am heavily involved here with v2, I kinda like where this sucker is sitting on its own, as well 😆)

**Comment by Mike-EEE** [comment]
Alright, much appreciation for this issue.  TBH I was tempted to be a wimp and "stale" it BUT I FOUGHT THROUGH AND NOW WE HAVE DOCUMENTATION. 😅

This has been released in the latest version which can be found here:
https://www.nuget.org/packages/ExtendedXmlSerializer/

In addition to XML Documentation in code we have a generated site based on that XML notation which can be found here:
https://extendedxmlserializer.github.io/documentation/

Further details on the release can be found here:
https://github.com/ExtendedXmlSerializer/home/releases/tag/3.0.0

If you run into any problems or have further questions, please feel free to open a new issue and we'll take a look.  Thank you for improving ExtendedXmlSerializer!
