### ISSUE TITLE
How can I serialize object type of DataTable ?

### ISSUE THREAD

**Issue by sand721** [ExtendedXmlSerializer/home#268]
I've got error when try to serialize an object type of DataTable:
 (non-abstract) class to activate.
"The serializer for type 'System.Globalization.CultureInfo' could not be found."

**Comment by Mike-EEE** [comment]
Ah this is a good one, @sand721 thank you for checking in and asking.

Unfortunately we do not have anything available for this specific type yet.  However, I do see that it implements `ISerializable` so one thought I have is to create a new extension method off of types that implement this interface as such:

```
new ConfigurationContainer().Type<DataTable>()
                            .UseClassicSerialization()
                            .Create()
```

And what this would do behind the scenes is use a classic `System.Xml.XmlSerializer` to handle the serialization for that type.

I'm not sure if that will even be possible/work, but a thought.  Let me know what you think.

**Comment by Mike-EEE** [comment]
Alright @sand721 I have a rough draft of this feature with a passing test here:

https://github.com/WojciechNagorski/ExtendedXmlSerializer/blob/e69d0f3f29b599e9b3f53e6f55c51173473697cc/test/ExtendedXmlSerializer.Tests/ReportedIssues/Issue268Tests.cs#L39-L65

Unfortunately, we are in the middle of re-configuring our preview feed so it's not yet available from a nuget perspective.  You are welcome to clone the code locally and try it from there, however.

**Comment by Mike-EEE** [comment]
FWIW this now available on our preview feed:

https://www.myget.org/F/wojtpl2/api/v3/index.json

**Comment by Mike-EEE** [comment]
This has been released in the latest version which can be found here:

https://www.nuget.org/packages/ExtendedXmlSerializer/

Further details on the release can be found here:

https://github.com/ExtendedXmlSerializer/home/releases/tag/3.0.0

If you run into any problems or have further questions, please feel free to open a new issue and we'll take a look.  Thank you for improving ExtendedXmlSerializer!
