### ISSUE TITLE
Bump net45 to net452

### ISSUE THREAD

**Issue by Mike-EEE** [ExtendedXmlSerializer/home#276]
Based on our discussion with #273, let's bump our `net45` build to `net452` as `net45` is no longer supported by MSFT:

https://dotnet.microsoft.com/download/dotnet-framework

**Comment by Mike-EEE** [comment]
Hey @WojciechNagorski I think we should make `2.1.26` the `2.2.0` release instead... what do you think?  It will include:

- Documentation (!)
- Fluent API adjustments (I've been having to do a few and in turn obsolete some calls -- examples [here](https://github.com/ExtendedXmlSerializer/ExtendedXmlSerializer/blob/master/src/ExtendedXmlSerializer/ExtensionMethods.Content.cs#L233-L235) and [here](https://github.com/ExtendedXmlSerializer/ExtendedXmlSerializer/blob/master/src/ExtendedXmlSerializer/ExtensionMethods.Content.cs#L415-L453))
- Minimum supported .NET Framework version (4.5.2)

That seems like enough to bump to a new minor version.  What do you think?

**Comment by WojciechNagorski** [comment]
@Mike-EEE It is a good idea. 👍

**Comment by Mike-EEE** [comment]
After some serious consideration over this, since this does introduce a breaking change (along with #285 and #189), it's better to version this to `v3.0.0` to be compliant with semantic versioning.

I know we had set "v3" to be a big re-write, but we'll have to adjust because of these changes.  I think it might be best to put that in a different repository in our new ExtendedXmlSerializer Organization, now that we have one.  Still thinking about it. :)
