### ISSUE TITLE
System.Reflection.Emit.Lightweight Makes UWP Grumpy

### ISSUE THREAD

**Issue by Mike-EEE** [ExtendedXmlSerializer/home#318]
Of course, UWP is a big grump all around. 😉

https://twitter.com/SuperJMN/status/1199987218733060096

**Comment by SuperJMN** [comment]
Removal of that dependency didn't make UWP much happier :(

# Repro steps:

1. Clone https://github.com/SuperJMN/SuppaDesigner.git
2. Checkout the 'exs' branch
3. Set 'Designer' as startup project
4. Select Release configuration and x64 platform
5. Run (build+run)
6. Upen startup, the app will throw: 

![image](https://user-images.githubusercontent.com/3109851/69808796-b1207280-11e8-11ea-9b1e-a51bfee36a2c.png)

**Comment by Mike-EEE** [comment]
Yeah the kicker here is `Release` mode in UWP.  This does not occur in `Debug`.  There's either a setting for compiler optimizations or we've found a bug. :|
