### ISSUE TITLE
NuGet updates from .Net Core 3.1 release

### ISSUE THREAD

**Issue by MagicAndre1981** [ExtendedXmlSerializer/home#335]
With release of .Net Core 3.1 some dependencies needs update:

System.Collections.Immutable from 1.6.0 to 1.7.0
System.ComponentModel.Annotations from 4.6.0 to 4.7.0
System.Runtime.CompilerServices.Unsafe from 4.6.0 to 4.7.0

**Comment by Mike-EEE** [comment]
Good point, @MagicAndre1981.  Thank you for keeping on top of this!  I will attend to these now.

I am not sure of our next release.  I want to wait a bit before others start reporting issues if anything.  I guess most of our work in `3.0.0` was the documentation, but you never know.  Keeping the "major" release major. 😆

Right now I'm putting this in a `3.0.2` milestone which is slated for the 24th of this month.  Preview will of course be available between then.

Open to any feedback/further suggestions around this. 👍

**Comment by Mike-EEE** [comment]
Working on a bot that does this automatically. 😁

But preview feed information for this issue has been posted here:
https://github.com/ExtendedXmlSerializer/home/pull/336#issuecomment-562035894

**Comment by MagicAndre1981** [comment]
> Good point, @MagicAndre1981. Thank you for keeping on top of this! I will attend to these now.

I noticed this yesterday when I checked for nuget updates and remembered the dependency issues here.

**Comment by Mike-EEE** [comment]
Yeah I didn't realize it until it was too late of course that 3.1 was launched.  Didn't connect the dots in time.

Anyways, now I am thinking that if no other issues are reported by next Tuesday the 10th I will send this out then.  I hate having so many releases bundled together (and forcing subsequent downloads on the developer side), but whatevs. 😏

**Comment by Mike-EEE** [comment]
Alright, this has been deployed to NuGet:
https://www.nuget.org/packages/ExtendedXmlSerializer/

Please let us know if you find any additional problems.  Thank you for improving ExtendedXmlSerializer with your contributions, @MagicAndre1981. 👍

**Comment by MagicAndre1981** [comment]
Please also update NReco.LambdaParser to version 1.0.11, the [1.0.10 failed to install to Xamarin projects](https://github.com/nreco/lambdaparser/issues/20#issuecomment-565433123) which results in install failure of ExtendedXmlSerializer.

**Comment by Mike-EEE** [comment]
Yeahh... check it out, @MagicAndre1981:

https://github.com/ExtendedXmlSerializer/home/pull/347#issuecomment-565461460

**Comment by MagicAndre1981** [comment]
thanks, the new version installs fine
