### ISSUE TITLE
Using EmitBehaviors.WhenModified with null Arrays causes NullReferenceException

### ISSUE THREAD

**Issue by Levi--G** [ExtendedXmlSerializer/home#337]
Repro on v3.0.1/Master:
```cs
var serializer = new ConfigurationContainer().Emit(EmitBehaviors.WhenModified).Create();
var xml = serializer.Serialize(new TestClass());
var deserialized = serializer.Deserialize<TestClass>(xml);
class TestClass
{
    public string[] Array { get; set; }
}
```
I think this is because the array gets compared with System.Linq.Enumerable.SequenceEqual which ofcourse does not accept null arrays.

Thank you for the great library!

**Comment by Mike-EEE** [comment]
Cool... thank you for the kind words, @Levi--G.  Just for that, I fixed your bug. 😆

If you'd like to try it, you can check out the details here:
https://github.com/ExtendedXmlSerializer/home/pull/338#issuecomment-563217803

If everything looks OK to you, I will get that merged into `master` for the deployment tomorrow.

**Comment by Levi--G** [comment]
Thanks!
<2h fix 😲 Must be the best support i received in years! :D
I will test/close tomorrow, altho there is no doubt this will have fixed the issue.
Keep up the good work! 👍

**Comment by Mike-EEE** [comment]
Thank you @Levi--G that means a lot!  I will update this thread upon deployment. 👍

**Comment by Levi--G** [comment]
Confirmed 100% working!
Thanks for the quick fix!

**Comment by Mike-EEE** [comment]
Sweeet... it has now been deployed to NuGet:
https://www.nuget.org/packages/ExtendedXmlSerializer/

Thank you for improving ExtendedXmlSerializer, @Levi--G!
