### ISSUE TITLE
EnableReferences might be causing incorrect deserialization

### ISSUE THREAD

**Issue by SuperJMN** [ExtendedXmlSerializer/home#341]
I have created a `ConfigurationContainer` configured like this:

```
serializer = new ConfigurationContainer()
    .UseAutoFormatting()
    .UseOptimizedNamespaces()
    .EnableParameterizedContent()
    .Type<Color>().Register().Converter().Using(ColorConverter.Default)
    .EnableReferences()
    .Create();
```

I have decided to "enable references" because my model potentially has circular references, but doing so makes deserialization act weird (results in empty object)

To see the problem, please, reproduce the issue with the step below:

1. Clone this repo: https://github.com/SuperJMN/Velcro-Designer.git
2. Run the application name **Designer**. It's a Universal Windows Application
3. Create an Ellipse using the toolbar like in the animation:
![Wb1J5ZgR8E](https://user-images.githubusercontent.com/3109851/70576325-e6de3780-1ba8-11ea-9076-b57c956cf177.gif)
4. You will see that the load operation doesn't load anything but a blank document (no Items).

However, if you comment out the [`.EnableReferences()` line](https://github.com/SuperJMN/Velcro-Designer/blob/67e036870b058b84e758310eefd763ca027ea732/Designer.Core/Persistence/ProjectStore.cs#L20):

**ProjectStore.cs**
![image](https://user-images.githubusercontent.com/3109851/70576474-4f2d1900-1ba9-11ea-87b8-ad79777d310d.png)

...and repeat the previous steps, you will notice the that document with the ellipse load perfectly.

## Tips
- **ProjectStore.cs** is exactly where the serialization/deserialization takes place. This is the class that will be called whenever you load/save a document.
- I've created a property `Id` for types inherited from the `Body` class. It may interfere with references 🤔

**Comment by Mike-EEE** [comment]
Cool!  Thank you for the information and for providing the code, @SuperJMN.  I am looking into this now. 👍

**Comment by Mike-EEE** [comment]
Alright @SuperJMN check it out:

https://github.com/ExtendedXmlSerializer/home/pull/342#issuecomment-564454665

Try that out to see if that works better for you.  The issue we ran into here was that the references extension was attempting to apply references to attribute values, which is not supposed to happen.  Shocking that we haven't seen that until now. 😁

Anyways, that *should* be fixed... let me know if you run into any further issues.

**Comment by SuperJMN** [comment]
It's working now. Big thanks! I'll test extensively the Circular References feature these days. I'll provide feedback in case it's not working as expected :)
