### ISSUE TITLE
Hot to set empty worspace on write xml?

### ISSUE THREAD

**Issue by BacchusD** [ExtendedXmlSerializer/home#345]
.Net  XmlSerializer.Serialize has parameter XmlSerializerNamespaces namespaces.
But ExtendedXmlSerializer can't do this.

**Comment by Mike-EEE** [comment]
Ah yes indeed @BacchusD we do not provide any mechanism for specifying namespaces as these are handled throughout the serialization process.  If you are working with existing XML there are some configurations that can be applied that will allow the serializer to read from classic XML serialization metadata, if required.

If you can provide more details around your scenario I can try my best to get you situated and on your way.

**Comment by BacchusD** [comment]
Okey, I can't specifying namespaces.
Can I create xml with empty namespace with ExtendedXmlSerializer?

**Comment by Mike-EEE** [comment]
So when you say empty namespace, are you meaning this?

`<MyClass xmlns="" />`

Or this?

`<MyClass />`

👆 If you want this, you can use implicit namespaces [as shown here](https://github.com/ExtendedXmlSerializer/home/wiki/Features#implicit-namespacestyping). 

If you are wanting `xmlns=""`, I am not sure how we could go about that... I'd have to think about it. :)

**Comment by Mike-EEE** [comment]
Seems like this question was answered.  Please let us know if you have any further questions and we will do our best to answer you. 👍  Closing for now.

**Comment by rogerfar** [comment]
@Mike-E-angelo sorry for kicking this back up, but my issue is similar so didn't want to open a new issue.

My XML has to look like this:

```
<pidx:Invoice pidx:transactionPurposeIndicator="Original" pidx:version="1.0" xmlns:pidx="http://www.api.org/pidXML/v1.0">
  <pidx:InvoiceProperties>
    <pidx:InvoiceNumber>11750</pidx:InvoiceNumber>
    <pidx:InvoiceDate>2020-10-05</pidx:InvoiceDate>
    <pidx:PartnerInformation partnerRoleIndicator="BillTo">
```

So I used to serialize like this:
```
            var serializer = new XmlSerializer(typeof(Invoice));

            var ns = new XmlSerializerNamespaces();
            ns.Add("pidx", "http://www.api.org/pidXML/v1.0");

            using var stringWriter = new Utf8StringWriter();

            serializer.Serialize(stringWriter, invoice, ns);

            var xml = stringWriter.ToString();

            return xml;
```

Is there a way to achieve the same behaviour?
