### ISSUE TITLE
How to custom root element on custom serialize?

### ISSUE THREAD

**Issue by BacchusD** [ExtendedXmlSerializer/home#346]
I have some class and need write his property on attribute.
But custom serializer create root element without customize.
And I can't rename root node name!

I need use POCO  i can't use XmlRootAttribute.
 For example: 
```
public class MyClass {
   public string SomeAttributeProperty {get;set;}

   public object SomeOtherProperty {get;set;}
}

public class MyClassSerializer : IExtendedXmlCustomSerializer<MyClass > {
    public TestClass Deserialize(XElement element) { 
                //now i have root node 
               //but it is not my custom node!!!
                var somePropertyValue = xElement.Attribute("SomeProperty")?.Value;
                return new MyClass { SomeProperty  = somePropertyValue };
    }

    public void Serializer(XmlWriter xmlWriter, MyClass obj) { 
            var rootElement= new XElement("MyClassNodeName");
            var someElement =  xElement.SetAttributeValue("SomeOtherProperty ");
            someElement.Value = obj.SomeOtherProperty ;
            rootElement.Add(someElement);
            rootElement.WriteTo(xmlWriter);
    }
}
```

On use ExtendedXmlSerializer serialize with MyClassSerializer will be created this xml : 
```
<MyClass xmlns="clr-namespace:Test;assembly=Test">
   <MyClassNodeName SomeProperty = "SomePropertyValue"> 
       <SomeOtherProperty> SomeOtherPropertyValue </SomeOtherProperty>
   </MyClassNodeName>
</MyClass>
```

But I need MyClassNodeName as root node!

**Comment by Mike-EEE** [comment]
Hi @BacchusD thanks for writing in... I have read your question a few times now and I am trying to understand.  When you say "I have xml:" do you mean you already have XML created and you need to deserialize with ExtendedXmlSerializer?  Or are you saying that is the generated XML by ExtendedXmlSerializer?

The use of `IExtendedXmlCustomSerializer` is more of a v1 serializer.  You should be using `ISerializer` registration [as demonstrated here](https://github.com/ExtendedXmlSerializer/home/wiki/Example-Scenarios#register-custom-serializer).

However, that should be used for very specialized purposes.  If you are not using existing XML, ExtendedXmlSerializer should be able to work with your object graph with very little configuration.  Let me know more details and I can see if I can assist with your scenario. 👍

**Comment by BacchusD** [comment]
I can't found documentetion by IFormatWriter and IFormatReader.
How to write attribute and child node with IFormatWriter ???

**Comment by Mike-EEE** [comment]
Ah good point, before we get into `IFormatReader` and `IFormatWriter`... I am trying to understand if you are working with existing XML and if you are running into problems with using ExtendedXmlSerializer serializing your object graph as-is.

You should be able to serialize and deserialize without having to use a custom serializer.

**Comment by Mike-EEE** [comment]
Here you go @BacchusD, I've added a passing test to show you, using your `MyClass` above:

https://github.com/ExtendedXmlSerializer/home/blob/a4b27ce46887e245140359b77aefcac0f61a28dc/test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue346Tests.cs#L11-L43

Please let me know if you have any questions around this.  The serializer _should_ "just work". :)

**Comment by BacchusD** [comment]
I have  two diffent program and need serialize DTO to xml and send to other program in some xml structure.

```
public class RootClass {
   public string SomeAttributeProperty {get;set;}

   public A ManyToOneReference {get;set;}

   public B OneToManyReference {get;set;}
   
}

public class A {  
    public string Name {get;set;}
}

public class B {  
    public string Name {get;set;}
}
```
I need xml in format:

```
<RootClassNodeName SomeAttributeProperty = "SomeAttributeProperty" Name="ManyToOneReference.Name" >
      <B Name = "BName1" />
       ......
      <B Name = "BNameN" />
  </RootClassNodeName>

```

XmlSerializer can't serialize A.Name to attribute. So i find ExtendedXmlSerializer.

If I set configuration via fluent API a can't configure attribute.
When I use IExtendedXmlCustomSerializer I can't custom root node.
When I use ISerializer<T> i can't use .Net parser such as XmlWriter or XDocument.

**Comment by Mike-EEE** [comment]
OK!  yes that will require a custom serializer of some sort.  I was wanting to make sure you weren't making it more difficult than it needs to be. :)

Let me see if I can get something working for you.

**Comment by Mike-EEE** [comment]
OK @BacchusD here you go.  In this case I would recommend using a content composer:

https://github.com/ExtendedXmlSerializer/home/blob/c65c94ce82b74dbefb28239fa7f3818458ee0ddb/test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue346Tests_Custom.cs#L14-L101

Essentially this allows you to intercept the serialization.  I've provided two examples for you, one that makes use of `UseAutoFormatting` (less markup) and one without.

For reference, this is what gets generated without `UseAutoFormatting`:

```
<?xml version="1.0" encoding="utf-8"?>
<Issue346Tests_Custom-RootClass Name="A" SomeAttributeProperty="Hello World!" xmlns="clr-namespace:ExtendedXmlSerializer.Tests.ReportedIssues;assembly=ExtendedXmlSerializer.Tests.ReportedIssues">
	<ManyToOneReference>
		<Name>A</Name>
	</ManyToOneReference>
	<OneToManyReference>
		<Name>B</Name>
	</OneToManyReference>
</Issue346Tests_Custom-RootClass>
```

This is what it looks like using it:

```
<?xml version="1.0" encoding="utf-8"?>
<Issue346Tests_Custom-RootClass Name="A" SomeAttributeProperty="Hello World!" xmlns="clr-namespace:ExtendedXmlSerializer.Tests.ReportedIssues;assembly=ExtendedXmlSerializer.Tests.ReportedIssues">
	<ManyToOneReference Name="A" />
	<OneToManyReference Name="B" />
</Issue346Tests_Custom-RootClass>
```

In either case, you can see the `Name="A"` is written to the root element, which I believe is what you are looking to accomplish.

Also, I have shown how to get access to `System.Xml.XmlReader` from the `IFormatReader` and the `System.Xml.XmlWriter` from the `IFormatWriter`, should you need to do more. 👍

Let me know if this gets you closer to solving your problem and/or if you have any further questions.

**Comment by Mike-EEE** [comment]
FWIW I took some time to improve the API around this @BacchusD and have a better implementation for you here:

https://github.com/ExtendedXmlSerializer/home/blob/34500c36638023b9c60d6960f52b6aca29e8e6a4/test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue349Tests.cs#L15-L88

It will require you to use a preview version of our package which you can use by following the directions seen here:

https://github.com/ExtendedXmlSerializer/home/pull/350#issuecomment-565587931

**Comment by Mike-EEE** [comment]
OK did some further improvements:

https://github.com/ExtendedXmlSerializer/home/blob/b8566a7f1a9cfb3795d48e4ef268fc3986207c19/test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue349Tests.cs#L15-L87

Install directions here:
https://github.com/ExtendedXmlSerializer/home/pull/351#issuecomment-565603428

FINAL ANSWER. 😆
