### ISSUE TITLE
MemberConfiguration.Order / Attribute Order

### ISSUE THREAD

**Issue by Lux44** [ExtendedXmlSerializer/home#355]
Hi, I would like to specify the Order of the attributes using Profiles, like: 
.Member(x => x.C).Name("Cc").Order(0). 
.Member(x => x.B).Name("Bb").Order(1)

For some reason it doesn't work for parent element, but it does work for child elements. I'm sure I'm missing something obvious. The whole code is here:
https://gist.github.com/Lux44/265d485c04a707fe72f853a0d8cda8bb

Desired xml:
```
 <OuterDataThings>
  <Cc>C</Cc>
  <Bb>B</Bb>
  <Aa>A</Aa>
</OuterDataThings>
```

Actual xml:
```
<OuterDataThings>
  <Aa>A</Aa>
  <Bb>B</Bb>
  <Cc>C</Cc>
</OuterDataThings>
```

**Comment by Mike-EEE** [comment]
Wow @Lux44 there are some days that I wonder how any of this manages to actually work at all... THIS IS ONE OF THOSE DAYS. 😆

I am not feeling too good about #352 either which is a really bad solution to that problem.  Seems like things like this would (should!) have popped up wayyyyyy sooner.

Ok, diatribe and whining aside, I am looking at this now. 😁

**Comment by Mike-EEE** [comment]
Alright @Lux44 this was actually pretty straight forward: we were simply not ordering members in the case of parameterized content.  This has been fixed and can be tried out by following the details here:

https://github.com/ExtendedXmlSerializer/home/pull/356#issuecomment-575742944

Please let me know if you have any questions and I'll do my best to help you out. 👍

**Comment by Lux44** [comment]
Works as expected, thank you very much!

**Comment by Mike-EEE** [comment]
Great!  I will push out a new version this weekend and update here accordingly.

**Comment by Mike-EEE** [comment]
This is now available on NuGet:
https://www.nuget.org/packages/ExtendedXmlSerializer/
