### ISSUE TITLE
struct serialization

### ISSUE THREAD

**Issue by aspektxxx** [ExtendedXmlSerializer/home#358]
When using version 2.0.24, given `var serializer = new ConfigurationContainer()
                                            .EnableParameterizedContentWithPropertyAssignments()
                                            .EnableReferences()
                                            .Create();` when root object for graph to serialize is struct `var v = new vector(new length(11), new length(13));` an exception is raised `System.ArgumentNullException : Value cannot be null.
    Parameter name: key`

required definitions:

```
    private class length
        {
            public length(int value)
            {
                Value = value;
            }

            public int Value { get;}
        }

    private struct vector
        {
            public vector(length l1, length l2)
            {
                L1 = l1;
                L2 = l2;
            }

            public length L1 { get; }
            public length L2 { get; }
        }
```

**Comment by Mike-EEE** [comment]
Nice grab, @aspektxxx!  That's a good point.  If we're serializing structures as the root instance then capturing references doesn't make sense.

Although structures can technically have references, with ExtendedXmlSerializer references are intended to be captured and monitored in the context of a parent/root (class) reference that serves as the start of the object/reference graph.

I have disabled the reference capturing in the case of structure roots.  If you would like to capture references the suggestion is to ensure the root object is a class/reference instead.

You can try out the preview of this here:
https://github.com/ExtendedXmlSerializer/home/pull/359#issuecomment-577622456

Please let me know if you encounter any issues using it and/or have any additional questions/suggestions.

**Comment by Mike-EEE** [comment]
Doh... looks like there's also an issue altogether with using `EnableReferences` with `EnableParameterizedContent`* ... looking into this now.

**Comment by Mike-EEE** [comment]
Boo @aspektxxx you sunk my battleship. 😆  While I can dodge the bullet with the structure root reference, combining `EnableReferences` with `EnableParameterizedContent`* leads to very bad things.  I have captured this in #360.

**Comment by aspektxxx** [comment]
Well @Mike-EEE the fix is working great. You can merge it.
PS: sorry for sinking your project. 🥇
