### ISSUE TITLE
Fatality: Combining EnableReferences with EnableParameterizedContent* is Not Supported

### ISSUE THREAD

**Issue by Mike-E-wins** [ExtendedXmlSerializer/home#360]
Per #358 ...

Looks like this is an unsupported scenario, meaning that if you use it, it will break.

Combining any flavor of `EnableParameterizedContent` with `EnableReferences` produces an unaccounted-for scenario, and will break.  I poked around to see if it is easily fixable, but alas it is not.  Capturing this here for those who might be running into this issue.

Unfortunately my time to devote to this project these days is not what it used to be... it's been a good run now, over 3 years.  I can fix the easy stuff but advanced scenarios such as this will have to be relegated to issues like this and pray that some brave soul might be willing to pick it up and submit a PR (doubtful due to the code but who knows).

Anyways, @WojciechNagorski ... we finally got bit by combining extensions.  We knew it was going to be a matter of time. 😁

This project sometimes makes me feel like this:

![](https://media.giphy.com/media/26ybwvTX4DTkwst6U/giphy.gif)

😏

**Comment by aspektxxx** [comment]
@Mike-EEE can you please elaborate on the issue? I'm using it on pretty big project to serialize project data. Its working without issues, at least for now. However, I would like to know possible drawbacks :)

**Comment by Mike-EEE** [comment]
Each one of these features works pretty good on their own.  It's combining them that is the problem.  For `EnableParameterizedContent` we do not instantiate an object but rather capture it in an `ActivationContext` object (basically a dictionary) and then instantiate the object once all the properties (constructor parameters) are captured.

Pairing this with references... when we capture a reference we store what is read from the reader.  In the case of `EnableParameterizedContent` being set, the reference is an activation context and not the reference to the expected object type because it has not been activated/instantiated yet.

So, this causes things to break down quite rapidly.  You can use one or the other, but not both concurrently at the moment, unfortunately.

**Comment by Mike-EEE** [comment]
For clarity @aspektxxx this test fails:

```
		[Fact]
		void Verify()
		{
			var serializer = new ConfigurationContainer().EnableParameterizedContentWithPropertyAssignments()
			                                             .EnableReferences()
			                                             .Create()
			                                             .ForTesting();

			var length = new length(11);
			var instance = new vector(length, length);

			var cycled = serializer.Cycle(instance);
			cycled.L1.Should().BeSameAs(cycled.L2);
		}

		class length
		{
			public length(int value)
			{
				Value = value;
			}

			public int Value { get; }
		}

		class vector
		{
			public vector(length l1, length l2)
			{
				L1 = l1;
				L2 = l2;
			}

			public length L1 { get; }
			public length L2 { get; }
		}
```

Note that `vector` has been made a `class` and that the same reference is sent to the constructor of `vector`:

```
var length = new length(11);
var instance = new vector(length, length);
```

If you are _not_ doing the above then it does work.  However if you use references with parameterized content as demonstrated above then it does throw an exception.

**Comment by aspektxxx** [comment]
@Mike-EEE thanks for explanation. This got me thinking about my project and I found bug where type with custom serializer is checked for references: [361](https://github.com/ExtendedXmlSerializer/home/issues/361)

**Comment by Mike-E-wins** [comment]
Good news... I was able to track this down with another issue #418.

You can check out a preview build here:

https://github.com/ExtendedXmlSerializer/home/pull/420#issuecomment-661956577

**Comment by Mike-E-wins** [comment]
Closing this as it was opened by me.
