### ISSUE TITLE
circular references are detected for types with custom serializer

### ISSUE THREAD

**Issue by aspektxxx** [ExtendedXmlSerializer/home#361]
Given complex type containing circular reference and custom serializer for that type `IExtendedXmlCustomSerializer<MyType>`, you get an exception that circular references are detected.

I belive types with custom serializer implemented should not be checked for references.

**Comment by Mike-EEE** [comment]
Ah are you saying you are handling the circular references with your custom serializer?  The problem here is that not every custom serializer will handle circular references.  So, is it a matter of enabling per-serializer?

I guess the better question is... is the exception keeping you from using a custom serializer altogether?  Providing some sample code would assist in helping determine a resolution for this scenario.

I am of course open to any suggestions, as well. :)

**Comment by aspektxxx** [comment]
Well, kind of. Maybe I was not clear enough by generalizing the problem. In my scenario, images are part of the data model I need to serialize. However, they also contain some metadata about that particular image. In that metadata, circular references may occur and they are beyond my control. The thing is, I don't want to store that image (that can potentially be up to 64k x 64k pixels) as Base64 in the XML. So I have IExtendedXmlCustomSerializer implemented for that image container, that will store image with embedded metadata on disk and return only relative path to that file that is stored in the serialized data model.

The problem is that ExtendedXmlSerializer is examining circular references in objects graph even for that type that is serialized in custom way.

**Comment by aspektxxx** [comment]
Example:

```
                void Verify()
		{
			var serializer = new ConfigurationContainer()
							 .EnableParameterizedContentWithPropertyAssignments()
							 .Type<AdornedImage>().CustomSerializer(new AdornedImageSerializer())
							 .Create();

			var instance = new AdornedImage();
			var serialized = serializer.Serialize(instance);
		}

		class AdornedImageSerializer : IExtendedXmlCustomSerializer<AdornedImage>
		{
			public AdornedImage Deserialize(XElement xElement)
			{
				return new AdornedImage();
			}

			public void Serializer(XmlWriter xmlWriter, AdornedImage obj)
			{
				
			}
		}

		class AdornedImage
		{
			public vector Vector { get; set; }

			public AdornedImage()
			{
				var data = new length(23);
				Vector = new vector(data, data);
			}
		}

		class length
		{
			public length(int value)
			{
				Value = value;
			}

			public int Value { get; }
		}

		private struct vector
		{
			public vector(length l1, length l2)
			{
				L1 = l1;
				L2 = l2;
			}

			public length L1 { get; }
			public length L2 { get; }
		}
```

**Comment by aspektxxx** [comment]
I would expect that the example above will work without issues and the exception would be thrown only when custom serializer is not registered

**Comment by Mike-EEE** [comment]
Yep, thinking this over and I agree with you @aspektxxx ... if the user is overriding the serialization that means they are assuming and given full control of it all.  They are, of course, agreeing to dive into the depths of XML document structures and the like.  So, they should be able to deal with circular references.

The next step, of course, is seeing if we can avoid the error.  I will look into this now.  Also, thank you for taking time to provide the sample code.  It makes things easier on my end with setting up the verification. 👍

**Comment by Mike-EEE** [comment]
Alright here you go for your review, @aspektxxx: https://github.com/ExtendedXmlSerializer/home/pull/362#issuecomment-579217518

**Comment by aspektxxx** [comment]
@Mike-EEE well, its working only if the type with custom serializer is the root object. If I change the example above to:
``` 
var instance = new DataHolder() { Image = new AdornedImage() };
var serialized = serializer.Serialize(instance);

                class DataHolder
		{
			public string Name { get; set; }
			public AdornedImage Image { get; set; }
			public int Index { get; set; }
		}

``` 
its still throwing an exception. :(

**Comment by Mike-EEE** [comment]
That's a good point @aspektxxx. 😁  Your use case is a good one as well as the type being detected as having multiple references is `length` and not `AdornedImage`.  The reference detection is very basic for performance reasons as this is running on (what is considered) the hot path.

As such, we report that multiple references are detected, but not the containing type in which these instances are found.  I, unfortunately, do not see a quick-and-easy way to resolve this but would gladly explore a PR that does if you (or someone else) can manage it. :)

**Comment by aspektxxx** [comment]
Okey @Mike-EEE, I got it working. Please look at it and tell me what you think :)

https://github.com/ExtendedXmlSerializer/home/pull/363

**Comment by Mike-EEE** [comment]
Dang, you are BRAVE @aspektxxx! 😆  I am slammed for today but I will take a look first thing tomorrow for you. 👍

**Comment by Mike-EEE** [comment]
Alright @aspektxxx [after a bit of a detour](https://github.com/gitextensions/gitextensions/issues/7706) I did manage to see your changes.  However, I am now a bit confused as the (currently) passing test `VerifyCustomSerialization_CircularReferenceOfRoot_DoesThrow` throws when above you state (and my understanding is) that you do _not_ want to throw in the case that a custom serializer is registered, correct?

**Comment by Mike-EEE** [comment]
FWIW I put the above question where it belongs, @aspektxxx. :P

https://github.com/ExtendedXmlSerializer/home/pull/363/files#r372844908

**Comment by Mike-EEE** [comment]
OK!  I got this shipped out for you, @aspektxxx ... thanks again for your patience and contributions here.  They are very much appreciated in light of my limited time of late.  Also, I got you in the [release notes](https://github.com/ExtendedXmlSerializer/home/releases/tag/3.1.1) and [CHANGELOG](https://github.com/ExtendedXmlSerializer/home/blob/master/CHANGELOG.md). 👍

3.1.1 can be found here:
https://www.nuget.org/packages/ExtendedXmlSerializer/
