### ISSUE TITLE
Getting this message : Not sure what needs to be done ?

### ISSUE THREAD

**Issue by scarryjerry** [ExtendedXmlSerializer/home#371]
An attempt was made to load a type with the fully qualified name of 'SyncAgents', but no type could be located with that name.'

I have a very complex class with embedded and cascading classes

class SyncAgents
   string value1
   string value2
   class class1
   class class2[]
       class class3[]
       string value  3
etc......

class2 is a embedded class in class1, and class3 is a embedded class in class 2.
I suspect I do not have this setup correctly for the complex class.

**Comment by Mike-EEE** [comment]
Hi @scarryjerry thanks for writing in... this sounds like the namespace is not being emitted correctly or that it doesn't exist in the document.  Are you creating the XML with ExtendedXmlSerializer or does it already exist and written by another xml serializer?

**Comment by scarryjerry** [comment]
The xml file already exists On Feb 14, 2020 2:59 PM, Mike-EEE <notifications@github.com> wrote:Hi @scarryjerry thanks for writing in... this sounds like the namespace is not being emitted correctly or that it doesn't exist in the document.  Are you creating the XML with ExtendedXmlSerializer or does it already exist and written by another xml serializer?

**Comment by Mike-EEE** [comment]
In that case you will have to do a little bit of work.  ExtendedXmlSerializer works best if it generates the document, but should be able to handle legacy documents.  Try using the `EnableImplicitTyping` call:

```
new ConfigurationContainer().EnableImplicitTyping(typeof(SyncAgents), typeof(Type1), typeof(Type1), etc... ).Create()
```

And see if that helps you out.  Let me know of any further issues you run into and I will do my best to assist you with them.

**Comment by Mike-EEE** [comment]
Closing this now as there has not been any activity with this question.  Please feel free to respond with any additional questions or comments with this issue, however, and I will do my best to assist you. 👍
