### ISSUE TITLE
collections initialized in constructor are not cleared on deserialization

### ISSUE THREAD

**Issue by aspektxxx** [ExtendedXmlSerializer/home#377]
Given test 
```
var serializer = new ConfigurationContainer().Create().ForTesting();
var instance = new Data1();
instance.MyCollection.Clear();
instance.MyCollection.Add("data4");
instance.MyCollection.Add("data5");
instance.MyCollection.Add("data6");
serializer.Cycle(instance).Should().BeEquivalentTo(instance);
```
where
```
class Data1
{
	public List<string> MyCollection { get; }
	public Data1()
	{
		MyCollection = new List<string>();
		MyCollection.Add("data1");
		MyCollection.Add("data2");
		MyCollection.Add("data3");
	}
}
```
I get 

> Expected member MyCollection to be a collection with 3 item(s), but {"data1", "data2", "data3", "data4", "data5", "data6"}"
"contains 3 item(s) more than"
"{"data4", "data5", "data6"}.

I would expect collection to contain only items 4 to 5.

**Comment by Mike-EEE** [comment]
This is a good catch, @aspektxxx ... we do capture this with basic values/references via the `EmitBehaviors.WhenModified` behavior, but I do not think it works for collections/lists.  I will look into this one but it might be more involved than a simple fix.

**Comment by Mike-EEE** [comment]
Yeah checking this one out @aspektxxx I am not sure the best way of supporting it.  The constructor is being called which is like calling a method on an object with initialization functionality being performed on it.  You're not going to get away from that and IMO it is bad practice for exactly these kind of scenarios.

FWIW I only use constructors to assign my internal `readonly` fields. :)  Any other functionality is considered bad practice and should be avoided.

That's me, however.  I am open to suggestions here but do not see how to fix it.

**Comment by aspektxxx** [comment]
@Mike-EEE Yeah, generally I agree. But! I have a very special case of a collection of fixed size that is modeling state of some old HW design and having init method on it is impractical at best. 
Anyway, I agree that doing general fix might not be easy if possible at all. Maybe checking if that type is ICollection<T> and clearing if so. But that's still not generally usable. Thinking about it, what about some extension that will call custom class that will handle this? Still, IMHO deserialization of such initialized collection that cannot be cleared should throw exception to ensure data integrity.

**Comment by Mike-EEE** [comment]
The first thought is that you might be able to take advantage of the serialization pipeline monitor here:

https://github.com/ExtendedXmlSerializer/home/wiki/Example-Scenarios#monitor-serialization-pipeline

When an object of a certain type is instantiated you can further perform actions upon it.  In this case you could clear the collection (or do whatever you need to do) when an object is activated.

Using this I was able to make the above pass, but I am not sure if that will work entirely for your scenario:

https://github.com/ExtendedXmlSerializer/home/blob/9fd535490c76509096dbee860a036618fa25cfda/test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue377Tests.cs#L14-L49

**Comment by Mike-E-angelo** [comment]
I wanted to check in with this issue, @aspektxxx ... was the pipeline monitor able to help you out?

**Comment by Mike-E-angelo** [comment]
I have adjusted this to a question as it seems existing functionality can assist you in your requirements here.  Please let me know if that is not the case and we can re-open and adjust accordingly. 👍
