### ISSUE TITLE
some collection types are not serialized

### ISSUE THREAD

**Issue by aspektxxx** [ExtendedXmlSerializer/home#379]
In the current contract in order to serialize collection, an ICollection IFace must be implemented and it must be possible to activate that type. I believe that collections should not be created by activator if created in constructor (e.g. ReadOnlyCollection). Also more general collections like IReadOnlyCollection or IEnumerable should be supported. In this case I propose they should be optionally emmited into XML when defined as public property (new extension). The filling of the collection can happen automatically if property is assigned ICollection type in constructor. If not, some custom deserializer should be implemented.

**Comment by Mike-EEE** [comment]
There's always the choice of leveraging the extension model if a particular type is not supported, @aspektxxx. :)

**Comment by aspektxxx** [comment]
@Mike-EEE I would like to extend it myself, but I find it almost impossible without help. The implementation model is IMHO hard to grasp, as the names of methods, variables and even classes are too generic.

**Comment by Mike-EEE** [comment]
Yeah I hear that @aspektxxx ... the extension model sort of "just happened" over time and it was me developing it without much documentation over several years.  I took a whack at it several months ago but as with anything it can always use improvement.

The best suggestion I have if you are patient enough is to go through the tests to see how they are used there, or anything implementing `ISerializerExtension` to get a feel for it.  Lots of material there but it's not documentation which would be ideal, I know.

**Comment by Mike-E-wins** [comment]
There hasn't been a lot of movement on this issue so I am channeling my inner Stale-bot (😅) and closing it for now.  I, of course, welcome any additional thoughts/comments around it so feel free to provide them, and we can take it from there.  👍
