### ISSUE TITLE
Serialize Expressions

### ISSUE THREAD

**Issue by Mike-E-angelo** [ExtendedXmlSerializer/home#382]
@SuperJMN asks: IS THIS POSSIBLE????

https://twitter.com/SuperJMN/status/1240035891520954372

**Comment by VitaliyMF** [comment]
LambdaParser is about formula-like expressions; it doesn't support constructions like for/foreach or anonymous functions. It's primary purpose is to handle expressions with dynamic (run-time) types harmonization, this is especially useful if these expressions may be entered by the end-users.

I don't think that LambdaParser is a right component for .NET Expression trees serialization/deserialization, this particular task may be solved in a more efficient way that guarantees that serialized Expression will be 1:1 the same as deserialized.

**Comment by Mike-EEE** [comment]
Wow cool!  A direct answer.  Thank you @VitaliyMF for taking the effort to let us know.  We will put some additional cycles towards figuring this out.

The interesting thing is that you can call `ToString` on an `Expression` and it will emit exactly as defined.  So it would seem serialization is spoken for and already available.  Are you aware of any expression parsers out there that would deserialize the provided string?

**Comment by VitaliyMF** [comment]
`Expression.ToString` internally uses https://github.com/dotnet/corefx/blob/master/src/System.Linq.Expressions/src/System/Linq/Expressions/ExpressionStringBuilder.cs

From the first sight, it doesn't look that `Expression.ToString()` always produces a valid C# syntax; if this is true parser that can convert this string back to Expression for all possible outputs is not possible, however for some sub-set of expressions you may try to write a parses by yourself.

**Comment by Mike-EEE** [comment]
Yeah that is a good point @VitaliyMF I have only tried simple expressions and nothing too involved.  Of course, having to write our own parsers is exactly what we're trying to avoid if it's already been done somewhere. 😁

**Comment by Mike-E-angelo** [comment]
Closing this as it will be bigger commitment than what I can attend to at the moment... will open up if someone would like to take a look into it.  Thanks again for assisting in ascertaining scope, @VitaliyMF!
