### ISSUE TITLE
Doesn't even start

### ISSUE THREAD

**Issue by yan-oreshchenkov** [ExtendedXmlSerializer/home#388]
I'm trying to use in my UnitTests (netcore 3.1):
```csharp
            _eserializer = new ConfigurationContainer()
                .UseAutoFormatting()
                .Create();
            var res = _eserializer.Serialize(new { Test = "test" });
```

and getting `Sprache.ParseException: 'Parsing failure: unexpected '<'; expected letter (Line 1, Column 1); recently consumed: `. What I do wrong?

I tried different options with `ConfigurationContainer` with the same result. I don't believe that it doesn't work at all.

**Comment by Mike-E-wins** [comment]
Hi @yan-oreshchenkov thank you for writing in... I will have to look into this but I do not believe we support `dynamic` objects as I believe you are attempting to do here.  It looks like it got far enough to serialize it, and even that is remarkable to me. 😆

I will see if I can poke around with this sometime tomorrow when I have more time but I am pretty sure this is an unsupported scenario.  However, it might be possible to support using an extension if you wanted to do so.

**Comment by Mike-E-wins** [comment]
Alrighty... I looked into this and this is definitely not a supported scenario at the moment.  We can improve the developer experience by providing a better exception message, but outside of that it will require additional work which is outside the limits of my time, unfortunately.
