### ISSUE TITLE
List<T> with complex objects (referential integrity, parameterized content) is not deserialized properly

### ISSUE THREAD

**Issue by feO2x** [ExtendedXmlSerializer/home#396]
Hey guys,
thanks for ExtendedXmlSerializer and the love and effort you put into it, I really think it's a great XML serializer.

I'm currently testing if ExtendedXmlSerializer is able to handle a complex object graph for a new project. This project uses a node graph that can be cyclic. Each node has a list of all linked nodes, and these links can either be unidirectional (if only one of two nodes links to the other one) or bidirectional (if both nodes link to each other).

I tried to serialize and deserialize this object graph with ExtendedXmlSerializer, but I encountered an issue. Please take a look at the following test (which uses xunit and FluentAssertions):

```csharp
public sealed class MissingItemsInCollectionTests
{
    private readonly ITestOutputHelper _output;

    public MissingItemsInCollectionTests(ITestOutputHelper output) => _output = output;

    [Fact]
    public void NodesListIsMissingNodes()
    {
        var xmlSerializer = new ConfigurationContainer().UseOptimizedNamespaces()
                                                        .EnableParameterizedContentWithPropertyAssignments()
                                                        .UseAutoFormatting()
                                                        .Type<Node>()
                                                        .EnableReferences(node => node.Id)
                                                        .Create();
        var node1 = new Node(1);
        var node2 = new Node(2).AddNode(node1, isBidirectional: true);
        var node3 = new Node(3).AddNode(node2, isBidirectional: false);
        node1.AddNode(node3, isBidirectional: false);
        var nodesList = new List<Node> { node1, node2, node3 };

        var xml = xmlSerializer.Serialize(new XmlWriterSettings { Indent = true, IndentChars = "    " }, nodesList);
        _output.WriteLine(xml);

        var deserializedNodesList = xmlSerializer.Deserialize<List<Node>>(xml);
        deserializedNodesList.Should().BeEquivalentTo(nodesList,  config => config.IgnoringCyclicReferences());
    }

    public sealed class Node : IEquatable<Node>
    {
        private readonly List<Node> _linkedNodes;

        public Node(int id) : this(id, null) { }

        public Node(int id, List<Node> linkedNodes)
        {
            Id = id;
            _linkedNodes = linkedNodes ?? new List<Node>();
        }

        public int Id { get; }

        public IReadOnlyList<Node> LinkedNodes => _linkedNodes;

        public Node AddNode(Node otherNode, bool isBidirectional = true)
        {
            if (otherNode == null)
                throw new ArgumentNullException(nameof(otherNode));
            if (ReferenceEquals(this, otherNode))
                throw new ArgumentException($"You cannot link a node {Id} to itself.");

            _linkedNodes.Add(otherNode);
            if (isBidirectional)
                otherNode.AddNode(this, false);
            return this;
        }

        public bool Equals(Node other) => !ReferenceEquals(null, other) && Id == other.Id;

        public override bool Equals(object obj) => ReferenceEquals(this, obj) || obj is Node other && Equals(other);

        public override int GetHashCode() => Id;

        public override string ToString() => "Node " + Id;
    }
}
```

In this test, i create three instances of the `Node` class and interconnect them. Node 1 has a bidirectional link to node 2 and a unidirectional link to node 3, node 3 links unidirectionally to node 2.

![interconnected node graph](https://user-images.githubusercontent.com/7884158/81782762-94f46180-94fa-11ea-8b4e-ce09f830a3e6.png)

When I run this test, the produced XML looks fine, but when the I deserialize the XML back to an object graph, then the following stuff happens:

- `deserializedNodesList` contains [ node 1, null, null ]
![Null was added to outer list](https://user-images.githubusercontent.com/7884158/81784185-c706c300-94fc-11ea-82ea-b624e40ef30f.png)
- Node 2 does not link back to node 1
![Missing link from node 2 to node 1](https://user-images.githubusercontent.com/7884158/81784434-249b0f80-94fd-11ea-882d-fa798d18e254.png)
- Node 3 does not link to node 2
![Missing link from node 3 to node 2](https://user-images.githubusercontent.com/7884158/81784717-91aea500-94fd-11ea-8c0b-846c4d92cc3d.png)

What keeps me wondering is that the link collections contain the right amount of entries, but all of them are null instead of the corresponding deserialized node instance. Did I forget to configure something properly, or is this is a bug in ExtendedXmlSerializer? Does this have something to do with https://github.com/ExtendedXmlSerializer/home/issues/360 (although no structs are involved)?

Thanks for your help in advance.

**Comment by feO2x** [comment]
I've tested  a further scenario and when `EnableParameterizedContentWithPropertyAssignments` is not configured on the XML serializer, it works flawlessly.

```csharp
[Fact]
public void NodesDto()
{
    var xmlSerializer = new ConfigurationContainer().UseOptimizedNamespaces()
                                                    .UseAutoFormatting()
                                                    .Type<NodeDto>()
                                                    .EnableReferences(node => node.Id)
                                                    .Create();
    var node1 = new NodeDto { Id = 1 };
    var node2 = new NodeDto { Id = 2 }.AddNode(node1, isBidirectional: true);
    var node3 = new NodeDto { Id = 3 }.AddNode(node2, isBidirectional: false);
    node1.AddNode(node3, isBidirectional: false);
    var nodesList = new List<NodeDto>{ node1, node2, node3 };

    var xml = xmlSerializer.Serialize(new XmlWriterSettings { Indent = true, IndentChars = "    " }, nodesList);
    _output.WriteLine(xml);

    var deserializedNodesList = xmlSerializer.Deserialize<List<NodeDto>>(xml);
    deserializedNodesList.Should().BeEquivalentTo(nodesList, config => config.IgnoringCyclicReferences());
}

public sealed class NodeDto
{
    public int Id { get; set; }

    public List<NodeDto> LinkedNodes { get; set; }

    public NodeDto AddNode(NodeDto otherNode, bool isBidirectional = true)
    {
        if (otherNode == null)
            throw new ArgumentNullException(nameof(otherNode));
        if (ReferenceEquals(this, otherNode))
            throw new ArgumentException($"You cannot link a node {Id} to itself.");

        LinkedNodes ??= new List<NodeDto>();
        LinkedNodes.Add(otherNode);
        if (isBidirectional)
            otherNode.AddNode(this, false);
        return this;
    }

    public override string ToString() => "Node " + Id;
}
```

**Comment by Mike-E-wins** [comment]
Wow!  Thank you for your detailed report and kind words, @feO2x!  It is much appreciated.

To be honest, I am amazed that _anything_ worked at all for you. 😆  Combining these two features has been identified as an incompatible feature combination with details provided in #360.

This is one of those inevitable gotchas with building an extensible system.  Well, rather, the v1 version of such (that is, the extension system in place now was built from scratch for ExtendedXmlSerializer v2 and continues to this day).  In a future version a better approach should be made to ensure that extensions fit better together and aware of the things they do to a given graph along with a capability matrix system, but alas, we do not have that currently.

Are you able to get what you need via your second provided configuration (without the use of `EnableParameterizedContent*`?  Otherwise, this is an identified issue and it, unfortunately, cannot be addressed without a significant amount of work.  By me, at least. 😁  (more @ #383)

**Comment by feO2x** [comment]
Credit where credit is due. I've read a few issues in your repo and the way you handle them as a maintainer is very friendly and exemplary.

BTW, I realized that you can even turn `EnableParameterizedContentWithPropertyAssignments` on and it would **not** have any negative consequences as long as the serialized instances that require referential integrity are mutable.

So I will leave my model mutable for now and tell my devs that they shouldn't change the ID when the corresponding instances are used in dictionaries.

I'm closing this issue as the problem is already captured in https://github.com/ExtendedXmlSerializer/home/issues/360.

Thanks for your help!

**Comment by Mike-E-wins** [comment]
Ahh thank you @feO2x that means a lot!  Happy to get this resolved, one way or another. :)  Thanks for stopping by and let us know if you run into any additional problems, particularly if they are easy to fix. 😁

**Comment by Mike-E-wins** [comment]
Hey there @feO2x ... good news!  I managed to figure out what is wrong here and have your test above passing in our suite now:

https://github.com/ExtendedXmlSerializer/home/blob/f3e47dae82f76e1a73ddb9de3d14a1feefed4176/test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue396Tests.cs#L12-L32

If interested, you can check out the build here:

https://github.com/ExtendedXmlSerializer/home/pull/421#issuecomment-661987667

Thought I would let you know.  Please let me know if you run into any further problems and I can look into it for you.  Re-opening and will close when pushed to NuGet. 👍

**Comment by Mike-E-wins** [comment]
I am actually astounded to see this work, considering the complexity of the graph! 😅  From first sight I definitely think "yep that should _totally_ break." 😂

**Comment by Mike-E-wins** [comment]
Guess I didn't need to really re-open this, but in any case, the fix has been deployed to NuGet here:
https://www.nuget.org/packages/ExtendedXmlSerializer/

If you encounter any further issues please let me know and I will take a look into it for you.  Closing (again) for now.

**Comment by feO2x** [comment]
Thanks for your efforts, I will take a look at it tomorrow!
