### ISSUE TITLE
How to configure all subtypes of a base class

### ISSUE THREAD

**Issue by gmkado** [ExtendedXmlSerializer/home#398]
Should inheritance be observed in the `ConfigurationContainer`?

Say I have the following setup:
```
    public abstract class CommandListDTO 
    {
        ...
        public abstract List<Type> AllowableCommandTypes { get; }
    }
 
    public class CommandList1: CommandListDTO
    {        
        public override List<Type> AllowableCommandTypes { get; } = new List<Type>
        {
            typeof(Command1),
            typeof(Command2),
        };
    }
```
Is there a way to configure all subclasses to i.e. ignore `AllowableCommandTypes`?  
I tried
                
```
.Type<CommandListDTO>().Member(x => x.AllowableCommandTypes).Ignore()   
```             

But it seems I have to type this out for all child classes to get it to work:
```
.Type<CommandList1>().Member(x => x.AllowableCommandTypes).Ignore()   
.Type<CommandList2>().Member(x => x.AllowableCommandTypes).Ignore()   
.Type<CommandList3>().Member(x => x.AllowableCommandTypes).Ignore()   
```

**Comment by Mike-E-wins** [comment]
Ah, good point @gmkado thank you for reporting this.  I believe we have locations in play that account for types, but members might be overlooked somewhere.  I will look into this to see if it's an easy fix.

**Comment by Mike-E-wins** [comment]
Alright good news bad news with this one.  Good news is I was able to provide a solution.  Bad news is that it's not entirely elegant. 😞

It basically involves overriding the default extensions used and returning a modified `IAllowedMembersExtension` (which I introduced).

You can find a passing test demonstrating this behavior here:

https://github.com/ExtendedXmlSerializer/home/blob/issues/other/i398/test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue398Tests.cs#L19-L143

It will involve adding some classes to your solution (again not elegant).  Anything further than this introduced breaking tests and/or changes.  I was/am also trying to avoid introducing/exposing any new classes than are what absolutely necessary.

Anyways, please take a look at the above and let me know what you think.  You can utilize the above changes by using this build as defined here:

https://github.com/ExtendedXmlSerializer/home/pull/399#issuecomment-640190653

**Comment by gmkado** [comment]
@Mike-E-wins thanks for the quick response!  Just tested your fix and it works for me.

**Comment by Mike-E-wins** [comment]
Sweet!  We'll see if we can get #397 working and aim for a release next Tuesday to NuGet. 👍

**Comment by Mike-E-wins** [comment]
v3.2.0 has been deployed:

https://www.nuget.org/packages/ExtendedXmlSerializer/

Please let us/me know if you run into any additional issues and I will look into them for you. 👍

**Comment by gmkado** [comment]
I didn't realize that this only fixes the inheritance issue for the `Ignore`  member configuration.  Is there a quick and easy way to modify the extension to work with e.g. `EmitWhen`?

**Comment by Mike-E-wins** [comment]
Ahhh good point @gmkado that's a different extension so it has its own set of rules/implementations.  I am not sure about quick/easy but I will find out. 😁  Captured in #411.  Please be sure to let me know of any others you find as well.
