### ISSUE TITLE
Apply `MemberComparer` to `AllowedMemberValuesExtension` (`EmitWhen`)

### ISSUE THREAD

**Issue by Mike-E-wins** [ExtendedXmlSerializer/home#411]
As per https://github.com/ExtendedXmlSerializer/home/issues/398#issuecomment-654098772 the same expectation should be applied to `EmitWhen` calls.

**Comment by Mike-E-wins** [comment]
Alright, see how this treats you, @gmkado:

https://github.com/ExtendedXmlSerializer/home/pull/412#issuecomment-654151254

🤞

**Comment by gmkado** [comment]
Thanks @Mike-E-wins  that did the trick!

**Comment by Mike-E-wins** [comment]
Welp, tried to sneak out a quick release, but that didn't go so well:

https://help.appveyor.com/discussions/problems/27700-release-assets-404-not-found

Hang tight with the preview build until we get this sorted.

**Comment by Mike-E-wins** [comment]
Simply re-running the build made it magically go through. 🤷‍♂️

This is now deployed on NuGet:
https://www.nuget.org/packages/ExtendedXmlSerializer/

Please let me know if you run into any further problems with this issue and I will take a look into it for you.  Thanks again for improving the quality of ExtendedXmlSerializer!
