### ISSUE TITLE
Type configuration being applied to all derived types of the abstract class that implements the member

### ISSUE THREAD

**Issue by gmkado** [ExtendedXmlSerializer/home#416]
Hi @Mike-E-wins not sure if this is a bug but I'm seeing somewhat the opposite of issue #398 where I configure the member of a derived type, but all types deriving from the base where the member is defined receive that configuration.  I tried both with and without the custom extension from #398 

Here's myrepro:
```
        [Test]
        public void MyTest()
        {
            var serializer = new ConfigurationContainer()
                .EnableImplicitTyping(typeof(Subject))
                .UseOptimizedNamespaces()
                .Type<SubjectA>().Member(x => x.Signature).Ignore() // <-- only configuring SubjectA, not SubjectB
                .Create();


            var subjects = new List<ISubject>();
            subjects.Add(new SubjectA { Signature = "testa" });
            subjects.Add(new SubjectB { Signature = "testb" });

            var str = serializer.Serialize(
                new XmlWriterSettings { Indent = true }, subjects);

            Console.WriteLine(str);
        }

        interface ISubject
        {
            string Signature { get; set; }
        }

        public abstract class BaseSubject : ISubject
        {
            public string Signature { get; set; }
        }
        public class SubjectA : BaseSubject
        {
        }
        public class SubjectB : BaseSubject
        {
        }
```

Output is:
```
<?xml version="1.0" encoding="utf-8"?>
<List xmlns:ns1="clr-namespace:SerializerTests;assembly=UnitTestSerializer" xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:arguments="ns1:Playground-ISubject" xmlns="https://extendedxmlserializer.github.io/system">
  <Capacity>4</Capacity>
  <ns1:Playground-SubjectA />
  <ns1:Playground-SubjectB />
</List>
```

I would have thought it would only ignore `Signature` on SubjectA

**Comment by Mike-E-wins** [comment]
Doh!  That doesn't look right.  Thank you for reporting this, @gmkado.  I appreciate your efforts here as I unfortunately do not have the time to thoroughly test as much as I should these days -- clearly! 😅

Looking into this now.

**Comment by Mike-E-wins** [comment]
Alright see if this fixes it for you, @gmkado:

https://github.com/ExtendedXmlSerializer/home/pull/417#issuecomment-661022091

If so I will get it into the release tomorrow.  Here's hoping it didn't break anything new. 😁

For some background, when we first started working on v2, there wasn't a `MemberInfo.ReflectedType` in the .NET Standard, so we were using `MemberInfo.DeclaredType`, which was leading to this issue.  None of our 1200+ (!) tests fail with the change so I am _hoping_ it's OK to change it as such. :)

**Comment by Mike-E-wins** [comment]
I should mention there was 1 test that did fail, but it was using the `MemberComparer` when in fact we're using the `InheritedMemberComparer` which first checks directly for the provided (reflected) member metadata, then for the inherited/base/declared version.

I've added a matrix that tests these different scenarios here:

https://github.com/ExtendedXmlSerializer/home/blob/issues/fix/i416/test/ExtendedXmlSerializer.Tests/ContentModel/Members/BlacklistMemberPolicyTests.cs#L51-L141

**Comment by gmkado** [comment]
@Mike-E-wins your response time continues to amaze me.

This fixed my simplified test scenario, but I think there might be some nuances to my actual model that is causing issues.  For one, the custom extension from #398 causes this to fail.  I removed it and am seeing inconsistent behavior for members defined in abstract classes vs interfaces.

I reworked my test to demonstrate this:
```
[Test]
        public void PlaygroundTest()
        {
            var serializer = new ConfigurationContainer()
                .EnableImplicitTypingFromAll<Parent>()
                .UseAutoFormatting()
                .EnableReferences()
                .UseOptimizedNamespaces()
                .Type<BaseSubject>().Member(x => x.IgnoreThisEverywhere).Ignore()     // <-- This doesn't work           
                //.Type<ISubject>().Member(x => x.IgnoreThisEverywhere).Ignore()   // <-- This works
                .Type<SubjectA>().Member(x => x.IgnoreThisForSubset).Ignore()
                .Create();

            var parent = new Parent
            {
                IgnoreThisForSubset = "Should see this",
                Commands = new List<ISubject>{
                    new SubjectA {
                        IgnoreThisForSubset = "Should NOT see this",
                        IgnoreThisEverywhere= "Should NOT see this"
                    },
                    new SubjectB {
                        IgnoreThisForSubset = "Should see this",
                        IgnoreThisEverywhere = "Should NOT see this"
                    }
                }
            };

            var str = serializer.Serialize(
                new XmlWriterSettings { Indent = true }, parent);

            Console.WriteLine(str);
        }


        public interface ISubject
        {
            string IgnoreThisForSubset { get; set; }
            string IgnoreThisEverywhere { get; set; }
        }

        public abstract class BaseSubject : ISubject
        {
            public string IgnoreThisForSubset { get; set; }
            public string IgnoreThisEverywhere { get; set; }
        }
        

        public class Parent : BaseSubject
        {
            public List<ISubject> Commands{ get; set; } = new List<ISubject>{};
        }

        public class SubjectA : BaseSubject
        {
        }

        public class SubjectB : BaseSubject
        {
        }
            string IgnoreThisForSubset { get; set; }
            string IgnoreThisEverywhere { get; set; }
        }

        public abstract class BaseSubject : ISubject
        {
            public string IgnoreThisForSubset { get; set; }
            public string IgnoreThisEverywhere { get; set; }
        }
        

        public class Parent : BaseSubject
        {
            public List<ISubject> Commands{ get; set; } = new List<ISubject>{};
        }

        public class SubjectA : BaseSubject
        {
        }

        public class SubjectB : BaseSubject
        {
        }
```

Output:
```
<?xml version="1.0" encoding="utf-8"?>
<Playground-Parent xmlns:sys="https://extendedxmlserializer.github.io/system" xmlns:exs="https://extendedxmlserializer.github.io/v2" IgnoreThisForSubset="Should see this">
  <Commands Capacity="4">
    <Playground-SubjectA IgnoreThisEverywhere="Should NOT see this" />
    <Playground-SubjectB IgnoreThisForSubset="Should see this" IgnoreThisEverywhere="Should NOT see this" />
  </Commands>
</Playground-Parent>
```

For my purposes I can get around this, but it seems like unintuitive behavior.

**Comment by Mike-E-wins** [comment]
Ah you are correct, @gmkado.  You will have to update the `MemberComparer` that you use in your extension to also use `ReflectedType`:

```
sealed class MemberComparer : IEqualityComparer<MemberInfo>
{
	readonly ITypeComparer _type;

	public MemberComparer(ITypeComparer type) => _type = type;

	public bool Equals(MemberInfo x, MemberInfo y)
		=> x.Name.Equals(y.Name) && _type.Equals(x.ReflectedType.GetTypeInfo(), y.ReflectedType.GetTypeInfo());

	public int GetHashCode(MemberInfo obj) => 0;
}
```

I've also got this added as a passing test here:

https://github.com/ExtendedXmlSerializer/home/blob/a83cc99bf64394fac8e1bd40f89270e9e086eb5b/test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue416Tests_Extended.cs#L77-L174

Hopefully that addresses your issue.  Please let me know if it doesn't and I will further investigate.

**Comment by Mike-E-wins** [comment]
The above fix has been pushed to NuGet:

https://www.nuget.org/packages/ExtendedXmlSerializer/

Please do let me know of any further issues you find around this or any other area and I will take a look into it for you.

Closing this for now.

**Comment by gmkado** [comment]
Thanks @Mike-E-angelo !
