### ISSUE TITLE
Properties are not filled in despite EnableParameterizedContentWithPropertyAssignments

### ISSUE THREAD

**Issue by maxkoshevoi** [ExtendedXmlSerializer/home#427]
Hi again =)

So now I'm facing denationalization issue. Type has parameterized constructor, it serializes fine, and on deserialization constructor is called, but no other properties are filled in:

![image](https://user-images.githubusercontent.com/6609929/90287432-8e221580-de80-11ea-9e86-8f3d7ec20537.png)

Updated repository, so it contains repro code for this issue: https://github.com/maxkoshevoi/ExtendedXmlSerializer-423

**Comment by Mike-E-angelo** [comment]
Hey! 😅  Thank you for taking the time to report these issues. 👍

To start, are you sure this is using the latest preview? (https://github.com/ExtendedXmlSerializer/home/pull/424#issuecomment-672267042)

I did try reproducing it but I have a passing test here:

https://github.com/ExtendedXmlSerializer/home/blob/c560a2a0d90e3b76af395c4bcf15d6de286176f3/test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue427Tests.cs#L12-L78

Is there a difference in the class/graph perhaps?  If you can provide some code again I can check it out further for you.

**Comment by maxkoshevoi** [comment]
It's not latest preview. It's latest stable (3.2.4). Can you try downloading provided repository and executing it?

**Comment by maxkoshevoi** [comment]
Oh, regarding the test. Your array type is wrong. It should be `NewTypeInfo` (base class of `NewFieldInfo`)

**Comment by Mike-E-angelo** [comment]
OK!  I see it now.  This is actually an issue with both `EnableParameterizedContent*` extensions.  Nice find. Tricky. :)  It also looks involved, so it might take a while.  I'll see if I can carve up some time this weekend to investigate further.  In the meantime, please do use arrays aligned with the same element type if you can manage.

**Comment by Mike-E-angelo** [comment]
Goodness, I gotta say that whenever a new issue is reported here now part of me freaks out as I have to dig through code I wrote over 3 years ago and get acclimated with how I was thinking back then which is NOTHING LIKE WOULD DO NOW. 😅

Anyways, this was a tricky one but I think I got it situated for you:
https://github.com/ExtendedXmlSerializer/home/pull/428#issuecomment-674376741

**Comment by maxkoshevoi** [comment]
Thank you so much for (in no particular order) fixing this so quickly and maintaining your 3-year-old repository.
If it wasn't for this NuGet, I don't know how would I do xml serialization.

So, fix for this and previous issues are releasing this Thursday, right? Or should I use pre-release version for now. I need to store child classes in base class array.

**Comment by Mike-E-angelo** [comment]
Thank you for the kind words, @maxkoshevoi 🙏  

Indeed, you should use the preview version for now until Tuesday, at which point I will release to NuGet.  Please let me know if you encounter any other/additional issues between now and then and I will look into them for you. 👍

**Comment by Mike-E-angelo** [comment]
I have merged in this PR so the main feed for the preview source should be used:

```
Install-Package ExtendedXmlSerializer -Version 3.2.4.4 -Source https://ci.appveyor.com/nuget/extendedxmlserializer-preview
```

Unfortunately, AppVeyor doesn't provide notifications on PR merges, only commits so I have to provide this manually.  The above should work, let me know if it doesn't otherwise.

**Comment by Mike-E-angelo** [comment]
This fix has been deployed to NuGet and can be found here:

https://www.nuget.org/packages/ExtendedXmlSerializer/

Thanks again for reporting and providing code towards discovering, diagnosing, and ultimately fixing this issue.  Please do let me know of any issues you find around this or any other issue and I will take a look into it for you.  Closing this issue for now.
