### ISSUE TITLE
Cannot deserialize consecutive CDATA elements

### ISSUE THREAD

**Issue by ms0815user** [ExtendedXmlSerializer/home#447]
There is an issue deserializing consecutive CDATA elements. I stumbled across this after serializing some text containing CDATA tags. While serializing closing ']]>' is correctly replaced with ']]]]><![CDATA[>' which were not treated properly in the deserialization process.
I could fix the bug in the XmlReader's `Content()` method as of below.

```csharp
public string Content()
{
	switch (_reader.NodeType)
	{

		case XmlNodeType.Attribute:
			return _reader.Value;
		default:
			if (_reader.IsEmptyElement && _reader.CanReadValueChunk)
			{
				Set();
				return string.Empty;
			}

			var isNull = IsSatisfiedBy(NullValueIdentity.Default);

			if (!isNull)
			{
				_reader.Read();
			}

			var result = isNull ? null : _reader.Value;

			if (_reader.NodeType == XmlNodeType.CDATA)
			{
				var sb = new StringBuilder(result);
				do
				{
					_reader.Read();
					Set();
					sb.Append(_reader.Value);

				} while (_reader.NodeType == XmlNodeType.CDATA);

				result = sb.ToString();
			}
			else if (!string.IsNullOrEmpty(result))
			{
				_reader.Read();
				Set();
			}

			return result;
	}
}
```

And here is the test:
```csharp
public sealed class Issue447Tests
{
	[Fact]
	public void Verify()
	{
		const string content = @"<?xml version=""1.0"" encoding=""utf-8""?><Issue447Tests-Subject xmlns=""clr-namespace:ExtendedXmlSerializer.Tests.ReportedIssues;assembly=ExtendedXmlSerializer.Tests.ReportedIssues""><Message><![CDATA[Hello ]]><![CDATA[world!]]></Message><Message2><![CDATA[Not ]]><![CDATA[this.]]></Message2></Issue447Tests-Subject>";

		var serializer = new ConfigurationContainer().Create()
													 .ForTesting();

		serializer.Deserialize<Subject>(content)
			.Message.Should().Be("Hello world!");
		
		serializer.Deserialize<Subject>(content)
			.Message2.Should().Be("Not this.");
	}

	sealed class Subject
	{
		[Verbatim]
		public string Message { get; set; }

		[Verbatim]
		public string Message2 { get; set; }
	}
}
``` 
All other tests passed successfully, too :wink:.

Edit: Full post of test class.

**Comment by Mike-E-angelo** [comment]
Hah!  Good catch, @ms0815user.  Thank you for reporting it.  I didn't even know this was possible. 😁  I will take a look at this and see if I can get it in for today's release. 👍

**Comment by Mike-E-angelo** [comment]
Alright @ms0815user you can try out this build here:
https://github.com/ExtendedXmlSerializer/home/pull/448#issuecomment-692705093

I _mostly_ went with your implementation, and did another check before creating the `StringBuilder` to avoid a  hotpath allocation unless necessary.  I did look into more performant solutions but they were either incomplete and/or required unsafe code.  Since this is a bit of an edge case I'm OK with the allocation if necessary.

FWIW, don't be afraid to submit a PR as well going forward.  Doing so will get your name listed as a PR author in our README/release notes upon release.  If you're into that sort of thing, that is. 😊

**Comment by Mike-E-angelo** [comment]
Alright, this has been posted to NuGet:
https://www.nuget.org/packages/ExtendedXmlSerializer/

Please let me know of any further questions/issues you encounter regarding this issue and I will reopen to take a look.  Closing for now.
