### ISSUE TITLE
Ignore property

### ISSUE THREAD

**Issue by Ganit20** [ExtendedXmlSerializer/home#475]
Hi i've started to use this serializator and my question is. Is there any way to ignore property in serialization? 
I've got a lot of read only properties and i do not need to serialize them.

**Comment by Mike-E-angelo** [comment]
Hey @Ganit20 welcome aboard and thanks for writing in.  You can indeed ignore properties.  Here is how to do this:

https://github.com/ExtendedXmlSerializer/home/blob/de270eb5706b5cabf761ea0037ab737ca02e0acb/test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue475Tests.cs#L10-L28

As far as read-only properties are concerned, those shouldn't get serialized by default unless they are list properties.  However, if you'd like to ignore them, using the above method call should do the trick.

Please let me know if you have any further questions around this and I will do my best to assist you. 👍

**Comment by Mike-E-angelo** [comment]
Looks like I have answered the question here so closing this issue for now.  Please do let me know if you have any further questions around this or anything ExtendedXmlSerializer-related and I will do my best to answer them for you.
