### ISSUE TITLE
AddMigration extension method for non-generic ITypeConfiguration

### ISSUE THREAD

**Issue by thomasjoscht** [ExtendedXmlSerializer/home#483]
Hey,

I try to manage my own MigrationSystem for registering migrations by XML model versions for my types. Therefore I've a Dictionary with type as key and a List of Migrations (classes based on `IEnumerable<Action<XElement>>`) as value. 

My problem is applying this migrations directly on `ConfigurationContainer` is not possible because I don't have generic `ITypeConfiguration` objects. My algorithmn is:
* Manage my Migration in MigrationSystem (outside in a static configuration manner).
* Iterate over `ConfigurationContainer` and try to call `AddMigration` for `ITypeConfiguration` - if a migration is configured for the type.

But ExtensionMethod `AddMigration` can only be called for `ITypeConfiguration<>` and not `ConfigurationContainer` Enumerator values of type `ITypeConfiguration`. I've also tried to directly use `With<MigrationsExtension>.Apply()` but this is internal.

Currently workaround is applying migrations directly during creation of `ContainerContainer`. Therefore I can call `Type<>` and then `AddMigration<>`. But this must be done for every type which feels wrong.

Does anyone have a better suggestion? Is it ok to provide a AddMigration extension method for ITypeConfiguration.

Regards
Thomas

**Comment by Mike-E-angelo** [comment]
Hey @thomasjoscht thanks for writing in with your issue.  I took a look around this and while there were several options, they all involved exposing internal classes.  So, I took the lesser of all evils so to speak and simply exposed `MigrationsExtension` for you.  You can try this build out and see if it treats you better here:

https://github.com/ExtendedXmlSerializer/home/pull/484#issuecomment-737699466

If that works OK for you, we can get this deployed out to NuGet next Tuesday. 👍

**Comment by thomasjoscht** [comment]
Hey @Mike-E-angelo, thx a lot for your super fast change. I've tried use of MigrationsExtensions and it works perfectly on my small prototype scenario. I will now implement rest of my migration system concept.

Regards Thomas

As note: I'm forced to apply migrations before calling `EnableReferences`. Otherwise the following error will occur:
```
System.InvalidOperationException: ReadSubtree() kann nur aufgerufen werden, wenn sich der Reader auf einem Elementknoten befindet.
  Stapelüberwachung: 
    XmlReader.ReadSubtree()
    Migrator.Get(IFormatReader parameter) Zeile 112
    Serializer.Get(IFormatReader parameter) Zeile 148
    Extensions.GetIfAssigned[T](IReader`1 this, IFormatReader reader) Zeile 12
    ....
```

**Comment by thomasjoscht** [comment]
As further suggestion: It should be possible to write an `AddMigration` method for non-generic version of `ITypeConfiguration` like this. Therefore MigrationExtension must not be exposed. What do you think?
```
public static ITypeConfiguration AddMigration(this ITypeConfiguration @this, IEnumerable<Action<XElement>> migrations)
   => @this.Root.With<MigrationsExtension>()
      .Apply(@this.Get(), migrations.Fixed())
      .Return(@this);
```

**Comment by Mike-E-angelo** [comment]
>Therefore MigrationExtension must not be exposed. What do you think?  

Oh my goodness @thomasjoscht I cannot believe I didn't think of that! 🤦‍♂️  Yes, that's a much better solution.  Let's do that instead.

Here is a build to try out with a non-generic version of `AddMigration`:
https://github.com/ExtendedXmlSerializer/home/pull/484#issuecomment-737991184

I guess my only concern is that there could be a resolution collision for the selected method now, since `ITypeConfiguration<T>` also implements `ITypeConfiguration`.  However, that doesn't seem to be the case as all assemblies built for .NET4.5, .NET 4.71, and .NET Core App 2.1, and they all selected the correct (generic) method.

So it would seem generic-based extension methods take precedent over non-generic-based equivalents.

**Comment by thomasjoscht** [comment]
Hey @Mike-E-angelo, thx a lot. My tests were successful. It think it should work with this new `AddMigration` methods. I'll let you know in case I need anything else in next few days. But for now my demand is covered 😊

**Comment by Mike-E-angelo** [comment]
OK @thomasjoscht we'll go with what we got and hope for the best. 🤞  If someone runs into an issue here we'll take those methods and move them to another namespace.  I'll be sure to update here if that is the case.  In the meantime, we can expect this to be deployed to NuGet next Tuesday and will update here when it has done so. 👍

**Comment by Mike-E-angelo** [comment]
This has been deployed to NuGet here:
https://www.nuget.org/packages/ExtendedXmlSerializer/

Closing for now.
