### ISSUE TITLE
How can I serialize a System.Collections.Immutable.ImmutableList<T>?

### ISSUE THREAD

**Issue by BSG-75** [ExtendedXmlSerializer/home#485]
For example, the following code will cause an exception, saying 
> The serializer for type 'System.Collections.Immutable.ImmutableList\`1[System.Int32]' could not be found.

I suspect other immutable types won't work either...

```cs
using ExtendedXmlSerializer;
using ExtendedXmlSerializer.Configuration;
using System.Collections.Immutable;
using System.IO;

class Test
{
    public ImmutableList<int> List { get; }
    public Test(ImmutableList<int> list)
    {
        List = list;
    }

    public void TestSerialize()
    {
        var serializer = new ConfigurationContainer()
            .UseAutoFormatting()
            .UseOptimizedNamespaces()
            .EnableImplicitTyping(typeof(Test))
            .EnableParameterizedContentWithPropertyAssignments()
            .Create();
        using var output = File.Create("test.xml");
        serializer.Serialize(output, new Test(new[] { 1 }.ToImmutableList()));
    }
}
```

**Comment by Mike-E-angelo** [comment]
Hey @BSG-75 thanks for writing in with the question and code.  We do have support for `ImmutableArray` and it was something we added at the outset of v2.  The thinking was that we'd wait until someone asked for other immutable types before adding more.  So here we are. 😁

I've added support for `InnutableList` and a build to try this out can be found here:
https://github.com/ExtendedXmlSerializer/home/pull/486#issuecomment-737773995

Please let me know if that looks good to you and if so we'll kick it out to NuGet in next Tuesday's build.

**Comment by BSG-75** [comment]
@Mike-E-angelo Thanks for the quick response! Now `ImmutableList` seems to be working well, but could you add support for `ImmutableDictionary` and `ImmutableSortedSet` too?

**Comment by Mike-E-angelo** [comment]
> Could you could add support for ImmutableDictionary and ImmutableSortedSet too?

![](https://media3.giphy.com/media/rmAxpa2ZCnRYs/giphy.gif?cid=ecf05e47ow4xtfvoic9lhg34lpu05xb44w3delbd02x1mnqw&rid=giphy.gif)

😁

I went ahead and added the whole gamut, why not:

- `ImmutableList`
- `ImmutableHashSet`
- `ImmutableSortedSet`
- `ImmutableDictionary`
- `ImmutableSortedDictionary`

Do note that since these would require additional checks for each type in a graph, I have put these now in a separate configuration method for performance/impact considerations: `EnableImmutableTypes`.  Example of these in action here:

https://github.com/ExtendedXmlSerializer/home/blob/43ce1d805d4b0812af0f674cf623cc9177c3ad38/test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue485Tests.cs#L12-L109

Please do try these out and verify these work on your end when you can get the chance:
https://github.com/ExtendedXmlSerializer/home/pull/486#issuecomment-738598901

If everything works and looks good to you, we'll get this out in Tuesday's build. 👍

**Comment by BSG-75** [comment]
> > Could you could add support for ImmutableDictionary and ImmutableSortedSet too?
> 
> ![](https://camo.githubusercontent.com/942c5f849317d184bd9af852fd8a766f27ca9a30e44c8fd982d25d3348a554d3/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f726d41787061325a436e5259732f67697068792e6769663f6369643d65636630356534376f7734787466766f6963396c686733346c7075303578623434773364656c6264303278316d6e7177267269643d67697068792e676966)
> 
> 😁

@Mike-E-angelo Eventually I managed to survive and climbed to the top of hill again, to make some tests ;)

The serialization / deserialization of these collections are working by themselves, except one thing:
When these collections are empty, nothing will be written to the xml (as expected, this is also my desired behavior)
But when we are deserializing back from the xml, a `NullReferenceException` will be thrown, probably because _ExtendedXmlSerializer_ failed to construct an empty immutable collection:
```cs
class TestCase
{
    public string Name { get; }
    public ImmutableList<TimeSpan> List { get; }

    public TestCase(string name, ImmutableList<TimeSpan> list)
    {
        Name = name;
        List = list;
    }

    public static void Test()
    {
        var x = new TestCase("ciao", ImmutableList<TimeSpan>.Empty);
        var sz = new ConfigurationContainer()
            .EnableParameterizedContent()
            .EnableImmutableTypes()
            .Create();
        var text = sz.Serialize(x);
        Console.WriteLine("XML: " + text);
        sz.Deserialize<TestCase>(text); // <--- Here, a exception will be thrown
    }

    // I tried to declare the following constructor hoping to resolve the issue,
    // but the deserialization still fails
    public TestCase(string name)
    {
        Name = name;
        List = ImmutableList<TimeSpan>.Empty;
    }
}
```

**Comment by Mike-E-angelo** [comment]
> Eventually I managed to survive and climbed to the top of hill again

Haha, to be certain, that was meant as a reference for me falling down the hill, as that is how I felt after digging through all my ghetto fabulous code from back in the day. 😆  It's a scene from The Princess Bride and I am sure I am entirely misappropriating it since it has been wayyyy too long ago since I have seen it.  It's the first thing I thought of, but I guess that is what I get for handling issues when I am geeked out on caffeine. 😁😇

ANYWAYS, the empty values were quite the challenge, but I think I figured it out for you.  Check this out and let me know if it works better for your scenario:

https://github.com/ExtendedXmlSerializer/home/pull/486#issuecomment-739288375

**Comment by BSG-75** [comment]
> Check this out and let me know if it works better for your scenario:
> [#486 (comment)](https://github.com/ExtendedXmlSerializer/home/pull/486#issuecomment-739288375)

@Mike-E-angelo Now it's working perfectly, thanks a lot!
By the way looks like it will cause some issues when using together with `EnableParameterizedContentWithPropertyAssignments` (instead of `EnableParameterizedContent`(, but personally I don't use `PropertyAssignments` yet, so it's not a problem for me xD

**Comment by Mike-E-angelo** [comment]
> PS: looks like it will cause some issues when using together with EnableParameterizedContentWithPropertyAssignments (instead of EnableParameterizedContent), but personally I don't use PropertyAssignments yet, so it's not a problem for me xD

Good catch @BSG-75!  I have posted a fix for this here:
https://github.com/ExtendedXmlSerializer/home/pull/486#issuecomment-739456933

**Comment by BSG-75** [comment]
> > PS: looks like it will cause some issues when using together with EnableParameterizedContentWithPropertyAssignments (instead of EnableParameterizedContent), but personally I don't use PropertyAssignments yet, so it's not a problem for me xD
> 
> Good catch @BSG-75! I have posted a fix for this here:
> [#486 (comment)](https://github.com/ExtendedXmlSerializer/home/pull/486#issuecomment-739456933)

All right, I'll try it when I'm wake up ;) 
By the way it _seems_ like that when encountering empty collections, ExtendedXmlSerializer will pass `null` instead of empty immutable container to the paramterized constructor during deserializing.
Right now I'm not able to verify if it's something wrong on my end, or it's a bug in ExtendedXmlSerializer, because I feel so much sleepy, I'll verify it when I wake up 😄

**Comment by Mike-E-angelo** [comment]
Interesting, @BSG-75 and by interesting I mean frightening. 😧  I did a quick sanity check on those tests in our suite and all 20 of them show that the objects being passed to the constructor are non-null and assigned.  If you do find the culprit on your end and can produce a test that demonstrates how to do so I can take a look into it for you.

**Comment by BSG-75** [comment]
@Mike-E-angelo Now I've checked it again, and it's not exactly what I've described before I fall asleep, but something more complicated 😅  
I have a class member which is null, so it didn't appear in XML. But when deserializing, the member will still be created, but with everything set to their default value (`null` in the case of `ImmutableList`)
```cs
class T
{
    public string Name { get; }
    public ImmutableList<int> List { get; }

    public T(string name, ImmutableList<int> list)
    {
        Name = name;
        List = list;
    }
}

class U
{
    public string Id { get; }
    public T? Member { get; }

    public U(string id, T? member)
    {
        Id = id;
        Member = member;
    }

    public static void Test()
    {
        var serializer = new ConfigurationContainer()
            .UseAutoFormatting()
            .EnableImmutableTypes()
            .EnableParameterizedContent()
            .Create();
        var settings = new XmlWriterSettings { Indent = true };

        var instance = new U("ciao", null);
        var xml = serializer.Serialize(settings, instance);
        Debug.WriteLine(xml);
        var deserialized = serializer.Deserialize<U>(xml);
        Debug.Assert(deserialized.Member is null); // Fails
        if (deserialized.Member is not null)
        {
            Debug.Assert(deserialized.Member.Name is not null); // Fails
            Debug.Assert(deserialized.Member.List is not null); // Fails
        }
    }
}
```

**Comment by Mike-E-angelo** [comment]
Very good catch @BSG-75 ... another one! :D  I did have to do some changes with how default type values were resolved and this slipped through.  Now we have tests to make sure this works as expected.

Please try this version out and see if you have any better luck with running your above test:

https://github.com/ExtendedXmlSerializer/home/pull/486#issuecomment-739569622

**Comment by BSG-75** [comment]
Yeah, now everything works as expected!

**Comment by Mike-E-angelo** [comment]
Alrighty, this has been deployed to NuGet here:
https://www.nuget.org/packages/ExtendedXmlSerializer/

Please do let me know of any issues you find and I will take a look into them for you.  Closing for now.
