### ISSUE TITLE
Bug in WithUnknownContent for elements with attribute name

### ISSUE THREAD

**Issue by thomasjoscht** [ExtendedXmlSerializer/home#491]
Hey,

I've found a bug which drives me crazy. First of all I haven't known the Feature `WithUnknownContent`. After model change my object was partly null. After setting `WithUnknownContent().Continue()` this was gone. JM2C: Perhaps it will make the library more robust with `Continue` as default.

After setting WithUnknownContent in some cases the object still was partly null. The reason I've found was a scenario where the Unknown content lies in root object and has name of a valid attribute. Then the `Continue` behavior will not work.

This TestCase can be used for reproducing the issue:
```csharp
namespace Test.XmlSerializer
{
    using System.Diagnostics;
    using System.Xml.Serialization;
    using ExtendedXmlSerializer.Configuration;
    using ExtendedXmlSerializer;
    using Microsoft.VisualStudio.TestTools.UnitTesting;

    [TestClass]
    public class BugAttributeInsteadOfElement
    {
        [TestMethod]
        public void Test()
        {
            var serializer = new ConfigurationContainer().WithUnknownContent().Continue().Create();

            // Create an object which have its Id as attribute
            var obj1 = new RootObjectIdAttribute() {Id = 1, Name = "RootObjectId 1"};
            var text1 = serializer.Serialize(obj1);
            Trace.WriteLine(text1);
            // <?xml version="1.0" encoding="utf-8"?><BugAttributeInsteadOfElement-RootObjectIdAttribute Id="1" xmlns="clr-namespace:Test.XmlSerializer;assembly=Test"><Name>RootObjectId 1</Name></BugAttributeInsteadOfElement-RootObjectIdAttribute>

            // Create an object which have its Id as element
            var obj2 = new RootObjectIdElement() {Id = 2, Name = "RootObjectId 2"};
            var text2 = serializer.Serialize(obj2);
            Trace.WriteLine(text2);
            // <?xml version="1.0" encoding="utf-8"?><BugAttributeInsteadOfElement-RootObjectIdElement xmlns="clr-namespace:Test.XmlSerializer;assembly=Test"><Id>2</Id><Name>RootObjectId 2</Name></BugAttributeInsteadOfElement-RootObjectIdElement>

            // TEST 1: Change object types which allows deserialize type
            var bugText1 = text2.Replace("RootObjectIdElement", "RootObjectIdAttribute");
            var bugObj1 = serializer.Deserialize<RootObjectIdAttribute>(bugText1);
            // RESULT 1: BUG encountered! Name is null although WithUnknownContent().Continue() is enabled
            Assert.IsNull(bugObj1.Name);

            // TEST 2: Set Id as Attribute and parallel as unknown element
            var bugText2 = bugText1.Replace("-RootObjectIdAttribute", "-RootObjectIdAttribute Id=\"1\"");;
            var bugObj2 = serializer.Deserialize<RootObjectIdAttribute>(bugText2);
            // RESULT 2: BUG also exists in case the attribute is set too
            Assert.IsNull(bugObj2.Name);

            
            // TEST 3: Rename element Id to Id2 - therefore it has not the same name as expected attribute
            var bugText3 = bugText1.Replace("<Id>", "<Id2>").Replace("</Id>", "</Id2>");
            var bugObj3 = serializer.Deserialize<RootObjectIdAttribute>(bugText3);
            // RESULT 3: Works just fine
            Assert.IsNotNull(bugObj3.Name);

            // => BUG happens only if an unknown content is determined which has same name as an expected attribute!
        }

        public class RootObjectIdAttribute
        {
            [XmlAttribute]
            public int Id { get; set; }

            public string Name { get; set; }
        }

        public class RootObjectIdElement
        {
            public int Id { get; set; }

            public string Name { get; set; }
        }
    }
}
```

The scenario above is very commen in case the annotation for a property changes to `XmlAttribute` and Migration is not used.

Regards
Thomas

**Comment by Mike-E-angelo** [comment]
WHEW you are giving me a run for my money on this extension @thomasjoscht 😅  It is good though.  I will always try to put my time due diligence-wise to see if a bug can be squashed.  As I mentioned anything, involving the reader makes me want to curl up into fetal position and cry myself to sleep.  This was no exception as it has to do with guts (and I mean that in all meaning of the term!) of the reader.

I think I managed a way to crawl through the muck and fix this particular issue, however. 🤞  Please check it out here and let me know if it works for you:

https://github.com/ExtendedXmlSerializer/home/pull/492#issuecomment-739323794

**Comment by thomasjoscht** [comment]
Hey @Mike-E-angelo, thx for your incredible good work! I've tested it with my application and it seems that bug is fixed. Everything runs nicely. I'm waiting for a new nuget release where this and #483 is integrated. I wish you have a nice advent.

**Comment by Mike-E-angelo** [comment]
Thank you for the kind words @thomasjoscht.  You can find that NuGet package here:
https://www.nuget.org/packages/ExtendedXmlSerializer/

Please do let me know of any issues you encounter and I will look into them for you.  Closing for now.
