### ISSUE TITLE
Question: Support for custom XmlIgnore attribute implementation

### ISSUE THREAD

**Issue by jhranac** [ExtendedXmlSerializer/home#497]
Hello, 

I'm looking into a way to serialize (and deserialize) properties based on them having an attribute assigned. But there are two scenarios  - and in one I want to serialize everything, in the other only the items (not) flagged with a custom attribute. 

I tried the Member extension, but that does not seem to do the trick and the Emit extension works only with the instance of the object it's checking - I need something that would let me decide based on MemberInfo - without me having to specify all properties manually. 

something along the lines of 
`container.Type<object>().ForAllMembers().EmitWhen( memberInfo => memberInfo.HasAttribute(xxxxx)`

Thanks

**Comment by Mike-E-angelo** [comment]
Ah unfortunately our member selection is deficient in this regard, @jhranac.  The `Emit` and `EmitWhen` calls are actually based on instance values and not their metadata.  The best suggestion I have for you is to cycle through the types you know you are going to serialize and utilize the `Ignore` method.

I have provided a quick demonstration of how you might go about doing this here:

https://github.com/ExtendedXmlSerializer/home/blob/2411ec3db65c45776db18c3edc137eb98f9d009f/test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue497Tests.cs#L12-L41

I would further recommend putting this in an extension method to help process many types if needed.

Not ideal, but this should allow you to get unblocked and attend to your scenario.  Please do let me know if you have any further questions/problems around this and I will do my best to assist.

**Comment by jhranac** [comment]
Thanks. That is something I've wanted to avoid, but it looks like there is no way around it. Works ok.
