### ISSUE TITLE
Is Inner Implicit Child List Content Supported via `XmlElementAttribute`?

### ISSUE THREAD

**Issue by BianChengNan** [ExtendedXmlSerializer/home#501]
As #243 has been closed. I think I'd better create a new one. sorry for interrupt.

Does ExtendedXml|Serializer support serialize/deserialize such xml structures now? really need this feature.

```
<MediaContainer size='1'> 
    <MediaItem Name='Name1' Id='1' />
    <MediaItem Name='Name2' Id='2' />
</MediaContainer>

public class MediaContainer
{
    [XmlAttribute("size")]
    public int Size { get; set; }

    [XmlElement("MediaItem")]
    public List<MediaItem> Items { get; set; }
}

public class MediaItem
{
    [XmlAttribute]
    public string Name { get; set; }

    [XmlAttribute]
    public string Id { get; set; }
}
```

**Comment by Mike-E-angelo** [comment]
Hi @BianChengNan thank you for writing in with your question here.  Unfortunately, this is related to a [known issue](https://github.com/ExtendedXmlSerializer/home/issues?q=label%3A%22known+issue%22+) specifically #461 which among other problems does not fully respect implicit inner content of an `XmlElementAttribute` for list items.

As this project is essentially in maintenance mode, the recommendation now is the same as it is in #243: use XSLT.  I acknowledge this is less than ideal and a pain, but it will allow you to cater to both legacy/classic serializer documents while still being able to use ExtendedXmlSerializer.

If you have any further questions around this scenario please do let me know and I will do my best to assist you.

**Comment by BianChengNan** [comment]
> Hi @BianChengNan thank you for writing in with your question here. Unfortunately, this is related to a [known issue](https://github.com/ExtendedXmlSerializer/home/issues?q=label%3A%22known+issue%22+) specifically #461 which among other problems does not fully respect implicit inner content of an `XmlElementAttribute` for list items.
> 
> As this project is essentially in maintenance mode, the recommendation now is the same as it is in #243: use XSLT. I acknowledge this is less than ideal and a pain, but it will allow you to cater to both legacy/classic serializer documents while still being able to use ExtendedXmlSerializer.
> 
> If you have any further questions around this scenario please do let me know and I will do my best to assist you.

copy that, thanks for your reply. really appreciate for your hard work and this excellent project.

**Comment by Mike-E-angelo** [comment]
Thank you very much for the kind words, @BianChengNan.  It is much appreciated. 🙏  Please do let me know if you have any further questions (either posting here or a new issue) and I will do my best to assist.  Closing this issue for now.
