### ISSUE TITLE
Deserialization State Exception When Reference Entity Has Attribute-based Property

### ISSUE THREAD

**Issue by feO2x** [ExtendedXmlSerializer/home#502]
Hey folks,

### About the issue

I encountered a weird behavior with Extended XML serializer 3.6.0 yesterday: we have a pretty complex model where some entities reference each other, thus we enabled references in the ConfigurationContainer. More precisely, our model consists of a map that is the container object for several other entities like nodes, obstacles, storage rows, etc. Consequently, the map has a collection for each entity type.

Everything worked fine (for several months) until we added a new property to one of our entities. After that, ExtendedXmlSerializer no longer set the aforementioned collection properties while deserializing a map.

### Minimal, complete, verifiable example

I have created a MCVE that you can find in this GitHub repo: https://github.com/Synnotech-AG/VweXmlSetCollectionsError

The repo contains the source code of ExtendedXmlSerializer as well as two additional projects: one of them is a simplified version of our core model, the other one is a test project with six tests. The repo contains two branches: if you checkout the `working-mcve` branch and run the tests, you will see that everything works as expected:

![Succesful tests in branch working-mcve](https://user-images.githubusercontent.com/7884158/109834552-99813680-7c42-11eb-9d59-de2b8c6aa34a.png)

If you then switch to the `failing-mcve` branch, you will see that we added a simple property to the `StorageLocation` class:

![New Type Property on StorageLocation class](https://user-images.githubusercontent.com/7884158/109835077-29bf7b80-7c43-11eb-939e-d9f4a734c787.png)

However if we run the tests again, some of the serialization tests fail:

![Failing tests after property was defined](https://user-images.githubusercontent.com/7884158/109835312-668b7280-7c43-11eb-9623-575a40daa9b4.png)

The one you should focus on is called `SerializeSmallMap` - it has the least instances involved.

### What I've tried so far

I have only put in a few hours, but this is what I gathered so far:

- The call to `Deserialize` does not throw, it simply does not set the collection properties on the `Map` object.
- It doesn't matter if you change the name of the new property
- If the property is nullable and has `null` assigned to it, then deserialization works. However, if it is any other string value, deserialization fails in the same way as described above.
- I tried to debug the tests to figure out what goes wrong but I couldn't really find the source of the issue. As far as I understand the ExtendedXmlSerializer source, you dynamically generate code at runtime and call these via delegates, but I still need to figure out where the code is generated that sets the collections for the map.
- I'm pretty sure that this issue is machine-independent. We encounter the same behavior on two dev machines as well as on our build server.

As always, thank you so much for your help in advance. I think this is a great project! I hope we can resolve this issue soon.

**Comment by Mike-E-angelo** [comment]
Doh @feO2x sorry to hear about this!  I did try to quickly look at your solution for anything obvious, but unfortunately it is complaining about `SynSerilogExtensions`.  It does not appear in NuGet:

https://www.nuget.org/packages?q=SynSerilogExtensions

Any guesses on where I can find this?

As for the exceptions.  This appears to be related to unknown content, but adding a new property shouldn't do this.  I won't know more until I can prod a little further.  But in the meantime, you should be able to use something to the effect of:


```
new ConfigurationContainer().WithUnknownContent().Throw().Create()
```

And it _should_ provide more details if it is encountering unknown content in your documents. 🤞

**Comment by Mike-E-angelo** [comment]
Also, you can try to `Continue` which will basically ignore unknown content and see if that helps any:

```
new ConfigurationContainer().WithUnknownContent().Continue().Create()
```

**Comment by feO2x** [comment]
Sorry for the inconvenience - I will update the solution first thing in the morning - I forgot that this Nuget package is only available on our internal server.

**Comment by feO2x** [comment]
I have updated the repo - you should be able to build it now.

**Comment by Mike-E-angelo** [comment]
Alrighty @feO2x thank you for that.

I am unclear on what is happening out of the gate, unfortunately.  It has to do something with how auto-formatting is being applied.  I will look into it further, but I was able to get all tests passing by configuring your container as such:

```
new ConfigurationContainer().UseOptimizedNamespaces()
	                        .EnableParameterizedContentWithPropertyAssignments()
			                .UseAutoFormatting()
			                .Type<StorageLocation>()
			                .Member(x => x.Type)
			                .Attribute(_ => false)
...
```

That forces your new property to serialize as an element, which for some reason works.  You can also remove `UseAutoFormatting` (and subsequent `Attribute` configuration) and that will also pass the tests:

```
new ConfigurationContainer().UseOptimizedNamespaces()
			                            .EnableParameterizedContentWithPropertyAssignments()
			                            .Type<Node>()
...
```

That should get you unblocked for now, assuming serializing in an element is OK for your scenario.  I will look further into this and update accordingly.

**Comment by feO2x** [comment]
Thank you for the quick help - I will try it out.

**Comment by Mike-E-angelo** [comment]
OK I have tracked this down to how the deserializer is processing reference/entity attributes when the reader context is within an attribute.  This _may_ be salvageable, no promises yet tho.

**Comment by Mike-E-angelo** [comment]
WHEW what a challenge. :)

Check out the following, @feO2x and let me know if it treats you better:
https://github.com/ExtendedXmlSerializer/home/pull/503#issuecomment-790637058

Please note that as part of that PR I have pulled in your tests/code from that repository and have made it a part of our test suite here going forward.  Please let me know if that is a problem and I can work with you on resolution.

**Comment by feO2x** [comment]
I've just checked it both on the MCVE as well as our total solution and it works successfully.

**Comment by Mike-E-angelo** [comment]
Great!  I will get this deployed to NuGet on Tuesday, our typical day of deployment.  Please feel free to use the preview build until this time and do let me know of any additional issues you encounter. 👍

**Comment by feO2x** [comment]
Is there any way I can sponsor you? You have been tremendously helpful, here as well as with other issues in the past. Couldn't find anything in this repo.

**Comment by Mike-E-angelo** [comment]
Oh wow, thank you for that!  I did consider doing the sponsorship thing at one point but ultimately decided against it.  I might though if others do ask for it, although my feeling is that I do not want to encourage it as it really is no longer a primary focus in my life (sad to say in this regard but happy in another... more on that below).  

I obviously do not do this for the money but more for the call of a neurotic sense of duty haha.  I started out this version of the project in some ways to prove myself as a developer.  Now I have all this code I have to support.  Amazingly, I somehow manage to make it work, but it's a kind reminder to be careful of what I wish for in life. 😉

BTW, if you _do_ want to support me, please sign up for the project that I am actively working on now:

https://starbeam.one

I am hoping to have something to share later on this year (August-ish, I am hoping 🤞).

Don't forget to use a burner address, I use this nifty service extensively, myself:
https://burnermail.io/

Thanks again for the kind thoughts!  It made my day.

**Comment by Mike-E-angelo** [comment]
FWIW we are currently blocked on a release due to NextRelease issues.  They are looking into it and should have something here in the next day, I am hoping. 🤞  I will update here accordingly.

**Comment by Mike-E-angelo** [comment]
Alrighty, after brushing off the dust from our CI we now have this pushed out to NuGet:
https://www.nuget.org/packages/ExtendedXmlSerializer/

Please do let me know of any issues you further encounter and I will take a look into it for you.  Closing for now.
