### ISSUE TITLE
Question: Does ExtendedXMLSerializer provide better error messages than System.Xml?

### ISSUE THREAD

**Issue by TheColonel2688** [ExtendedXmlSerializer/home#507]
Does ExtendedXMLSerializer provide better error messages than System.Xml?

For example, will it tell me what the name of the Property/Field is that is throwing a parsing error? Will it actually give correct Row Numbers and Column positions for errors? (system.xml does neither of these things)

**Comment by Mike-E-angelo** [comment]
Hey @TheColonel2688 thanks for writing in with your question.  I wouldn't know exactly about being _better_ than System.Xml, but we do offer some configurations that improve the handling of content.  Specifically, we have the `EnableMemberExceptionHandling()` and `WithUnknownContent().Throw()` methods while configuring the container.

For your review, I have added an example of this here that demonstrates these, along with a passing test for a `LinePosition` value when the exception occurs:

https://github.com/ExtendedXmlSerializer/home/blob/cd0cd55be4ae08a4f51e525e55a4f096ea6f170b/test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue507Tests.cs#L12-L29

Please let me know if you have any further questions around these features and/or scenario and I will do my best to assist.

**Comment by Mike-E-angelo** [comment]
There hasn't been activity here for some time so I will close this for now.  If you have any further/additional questions please leave a comment here and we can take a further look at it. 👍
