### ISSUE TITLE
documentation question: applying config only to specific paths in the XML

### ISSUE THREAD

**Issue by binary1230** [ExtendedXmlSerializer/home#509]
Hi, thanks again for this awesome library!

I had a question about applying configuration to specific paths in the XML. I decided to reach out to ask about this because I feel like I might just be missing something simple.

What I'm trying to do is serialize a specific dictionary in my app to serialize some ints as Hexedecimal in the XML. I wrote a converter that's fairly simple, but, I'm having trouble getting it to apply ONLY to one specific path in the XML.

Here's a pseudocode example (the actual structure here is silly and contrived, it's just to demo the concept)
```c#
class People {
   // this is the Dictionary that sometimes I want the Key output as Decimal and sometime as Hex
   Dictionary<int, string> IdsToNames {get; set;}
}

class Company {
  People Employees {get; set;} = new();
}

class Contacts {
  People ContactInfo {get; set;} = new();
}

class Root {
   Company Company {get; set} = new();  // Should output IDs as Decimal
   Contacts Vendors {get; set} = new(); // Should output IDs as Decimal
   Contacts CustomerLeads {get; set} = new(); // Should output IDs as Hex
}
```

What I'm trying to do is be able to set some output formatting/converter/migration on ```Root.Company.Employees.IdsToNames``` so that it outputs the IDs as Hexedecimal in the generated XML.

So the mocked up output XML (vaguely) looks like this:

```xml
<Root>

  <Company>
    <Employees>
       <IdsToNames>
           <!-- output keys as Decimal (regular) -->
           <sys:Item Key="64" Value="Edgar" />
           <sys:Item Key="128" Value="Evelyn" />
       </IdsToNames>
    </Employees>
  </Company>

  <Vendors>
    <ContactInfo>
       <IdsToNames>
           <!-- output keys as Decimal (regular) -->
           <sys:Item Key="129" Value="Vicky" />
           <sys:Item Key="236" Value="Victor" />
       </IdsToNames>
    </ContactInfo>
  </Vendors>

  <CustomerLeads>
    <ContactInfo>
       <IdsToNames>
           <!-- output keys as Hex (special) -->
           <sys:Item Key="0x41" Value="Larry" />
           <sys:Item Key="0xF2" Value="Lisa" />
       </IdsToNames>
    </ContactInfo>
  </CustomerLeads>

</Root>
```

--------

Basically my question mostly boils down to, is there a way in a ```ConfigurationContainer``` to select, say, ```Root.CustomersLeads.ContactInfo.IdsToNames.Keys``` and apply configuration (perhaps IMemberConfiguration or something like it) to JUST that path? i.e. something like this:
```c#
new ConfigurationContainer()
    .Type<Root>()  // real
    .Member(member => member.CustomerLeads)  // real 

    // is there a way to do something like.....
    // this?
    .SubMember(subMember => subMember.ContactInfo.IdsToNames.Keys)
   // or maybe like this?
   .Condition(node => node.Path == "Root/CustomersLeads/Contacts/IdsToNames")


   .Register().Converter(MyIntToHexConverter) // something like this
```

I can't just use ```.Type<People>.Member(m=>m.IdsToNames)``` here, since it would affect all ```People``` and I just want to affect the one.

It would also be OK if in the Converter I could do something like:
```c#
var specificPathICareabout = "Root/CustomersLeads/Contacts/IdsToNames";
if (CurrentPath == specificPathICareabout) {
  // do hex conversion for int output
} else {
  // do regular int parsing
}
```

---

Just for actual context, my real-world application for this is a reverse engineering tool which is tagging tons of different stuff using Dictionary<int, string> in a binary file (like memory locations, offsets, etc).  Some of that I'd like to be written in hex to the project XML (which is easier for humans to review/merge in a diff), and some of it would be better as ints.  I'm trying to make turning this on or off for various fields user-configurable.

The hex/dec thing is a silly use for this, but, in the future, I might need this kind of selection functionality for migration purposes.

Thanks for your time, sorry I keep posting these elaborate examples :)

**Comment by Mike-E-angelo** [comment]
> Thanks for your time, sorry I keep posting these elaborate examples :)

Not a problem @binary1230.  I'm actually amazed -- and yes, maybe even a little horrified 😅 -- to see people actually using software that I helped put together.

As far as your scenario, it is indeed quite advanced and unfortunately outside of the current capabilities of our existing API.  FWIW, I'm all for putting the magic in the serializer and keeping the domain model as "plain" as possible, but in this case, you might have to specialize the model to accomplish your directives.  

In your case, I would apply a specialized dictionary for your hex-based values.  Something like the following:

https://github.com/ExtendedXmlSerializer/home/blob/19a610992dbdcb33f78f57b5715583b5a82a4811/test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue509Tests.cs#L13-L87

From there, you can further customize how the keys are emitted and provide better customization around their values.  

BTW, I joke about being horrified but I am still equally amazed that the above _actually works_, too. :)

In any case, I do appreciate the kind words.  Please do let me know if you have any further questions/issues with the above and we can take it from there.

**Comment by binary1230** [comment]
Wow! thanks for the example, and I think this approach is solid for what we're doing. I was thinking along those lines might be the way to go, don't mind changing the model a bit to fit the output.

I know the feeling regarding people using your software, it's happening to me upstream on the project I'm using this for and I'm flipping out a bit too : )

Digging into ExtendedXmlSerializer source has opened my eyes more to the configuration/container based style of C# coding, definitely making it a point to dig into that some more.

Thanks again!

**Comment by Mike-E-angelo** [comment]
Ah yeah... it's really predicated on the [decorator pattern](https://en.wikipedia.org/wiki/Decorator_pattern).  It's my BBQ sauce of software design -- it goes good with anything. 😆

In any case, glad to hear we got you in the right direction here.  Do let me know if you have any additional/further questions and I will take a look into it for you.  Closing this for now.
