### ISSUE TITLE
Is there a way to use the serialiser in parallel tasks?

### ISSUE THREAD

**Issue by imperiobadgo** [ExtendedXmlSerializer/home#511]
First of all, thank you again for this brilliant project!

I was wondering if an object can be serialised faster if it is divided into smaller parts beforehand and serialised independently in parallel tasks. The resulting parts could then be integrated and saved in a zip archive with the info where they were positioned in the original object. 

However, I have observed the following about this:
If I use a Parallel.ForEach loop, all parts are serialised at the same time, but each individual operation takes longer than if I serialise the original object once.
If I serialise the result parts sequentially, it also takes much longer than serialising only the original object.

Measured average Results on my Machine with the Settings in my Example:

normal = 1356 ms
extraced = 5813 ms
parallel = 3061 ms

I am now very confused by these results and would like to know if the serialiser internally has any optimisations that override these ideas.

In the following i provided my testclasses.

**Comment by imperiobadgo** [comment]
`
using ExtendedXmlSerializer.Configuration;
using ExtendedXmlSerializer.ContentModel.Conversion;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Serialization;

namespace ExtendedXmlSerializer.Tests.Performance
{
  public static class ParallelPerformance
  {
    public static int SEED = 65465;

    public static int GUIDMINCOUNT = 10;
    public static int GUIDMAXCOUNT = 30;

    public static int ITEMMINCOUNT = 2;
    public static int ITEMMAXCOUNT = 5;

    public static int ITEMRESULTMINCOUNT = 3;
    public static int ITEMRESULTMAXCOUNT = 5;

    public static int LINEMINCOUNT = 10;
    public static int LINEMAXCOUNT = 80;
    public static int LINEITEMRESULTMINCOUNT = 5;
    public static int LINEITEMRESULTMAXCOUNT = 10;

    public static int SEGMENTMINCOUNT = 5;
    public static int SEGMENTMAXCOUNT = 50;
    public static double POINTRANGE = 1000;
    public static int CONTENTRANGE = 425;

    public static void Run()
    {
      Random r = new Random(65465);
      Project project = new Project();

      //Build some complex Object graph with many items
      for (int i = 0; i < 2; i++)
      {
        project.Structure.Add(new Grouping.Group(r));
      }


      IConfigurationContainer config = new ConfigurationContainer();

      //Add a special converter
      config.Type<List<Guid>>().Register().Converter().Using(new XmlGuidListConverter());
      var serializer = config.Create();

      List<double> measuredTimes = new List<double>();
      List<double> measuredExtractedTimes = new List<double>();
      List<double> measuredParallelTimes = new List<double>();
      var runs = 3; //Multiple runs for average time

      //normal run with serializing the whole project
      for (var index = 0; index <= runs; index++)
      {
        Stopwatch watch = new Stopwatch();
        watch.Start();

        var projectOutput = serializer.Serialize(new XmlWriterSettings() { Indent = true }, project);

        watch.Stop();
        var time = watch.Elapsed.TotalMilliseconds;
        Debug.WriteLine($"{time} ms: Sequential {index}");
        measuredTimes.Add(time);
      }


      //Extract Items (in a real world scenario a mapping to the original position of each time is needed)
      List<object> itemsToSerialize = new List<object>();
      itemsToSerialize.Add(project);
      foreach (var group in project.Structure)
      {
        while (group.Children.Count > 0)
        {
          var item = group.Children[0];
          itemsToSerialize.Add(item);
          group.Children.Remove(item);
        }
      }

      //Serialize extracted Items in sequence
      for (var index = 0; index <= runs; index++)
      {
        Stopwatch watch = new Stopwatch();
        watch.Start();

        foreach (var item in itemsToSerialize)
        {
          var projectOutput = serializer.Serialize(new XmlWriterSettings() { Indent = true }, item);
        }

        watch.Stop();
        var time = watch.Elapsed.TotalMilliseconds;
        Debug.WriteLine($"{time} ms: Extracted {index}");
        measuredExtractedTimes.Add(time);

      }

      //Serialize extracted Items in parallel
      ParallelOptions options = new ParallelOptions() { MaxDegreeOfParallelism = 8 };
      for (var index = 0; index <= runs; index++)
      {
        Stopwatch watch = new Stopwatch();
        watch.Start();

        Parallel.ForEach(itemsToSerialize, options, item =>
        {
          var projectOutput = serializer.Serialize(new XmlWriterSettings() { Indent = true }, item);
        });

        watch.Stop();

        var time = watch.Elapsed.TotalMilliseconds;
        Debug.WriteLine($"{time} ms: Parallel {index}");
        measuredParallelTimes.Add(time);
      }
      double normal = measuredTimes.Average();
      double extracted = measuredExtractedTimes.Average();
      double parallel = measuredParallelTimes.Average();

    }

  }

  public class XmlGuidListConverter : IConverter<List<Guid>>
  {
    public bool IsSatisfiedBy(TypeInfo parameter)
    {
      return typeof(List<Guid>).GetTypeInfo().IsAssignableFrom(parameter);
    }

    public List<Guid> Parse(string data)
    {
      string[] items = data.Split(new string[] { " " }, StringSplitOptions.RemoveEmptyEntries);
      List<Guid> result = items.Select(item => Guid.Parse(item)).ToList();
      return result;
    }

    public string Format(List<Guid> instance)
    {
      var items = instance.Select(item => item.ToString()).ToArray();
      var result = string.Join(" ", items);
      return result;
    }
  }


  class Project
  {
    public Project()
    {
      Name = "This is a great Project";
    }

    public string Name { get; set; }
    public List<Grouping.Group> Structure { get; set; } = new List<Grouping.Group>();



  }

  namespace Grouping
  {
    class Group
    {
      public Group() { }

      public Group(Random r)
      {
        int count = r.Next(ParallelPerformance.ITEMMINCOUNT, ParallelPerformance.ITEMMAXCOUNT);
        for (int i = 0; i < count; i++)
        {
          Children.Add(new ItemSpecifics.Item(r));
        }
      }


      public List<ItemSpecifics.Item> Children { get; set; } = new List<ItemSpecifics.Item>();

    }
  }

  namespace ItemSpecifics
  {
    class Item
    {
      public Item() { }

      public Item(Random r)
      {
        Id = Guid.NewGuid();
        ContentA = new LargeContent(r);
        ContentB = new LargeContent(r);

        int count = r.Next(ParallelPerformance.ITEMRESULTMINCOUNT, ParallelPerformance.ITEMRESULTMAXCOUNT);
        for (int i = 0; i < count; i++)
        {
          Results.Add(new OtherContent.ItemResult(r));
        }
      }

      public Guid Id { get; set; }

      public LargeContent ContentA { get; set; }

      public LargeContent ContentB { get; set; }

      public List<OtherContent.ItemResult> Results { get; set; } = new List<OtherContent.ItemResult>();

    }

    class LargeContent
    {
      public LargeContent() { }

      public LargeContent(Random r)
      {
        int count = r.Next(ParallelPerformance.LINEMINCOUNT, ParallelPerformance.LINEMAXCOUNT);
        for (int i = 0; i < count; i++)
        {
          Lines.Add(new LineMathematics.Line(r));
        }
      }

      public List<LineMathematics.Line> Lines { get; set; } = new List<LineMathematics.Line>();

    }

  }

  namespace OtherContent
  {
    class ItemResult
    {
      public ItemResult() { }

      public ItemResult(Random r)
      {
        A = r.Next(-ParallelPerformance.CONTENTRANGE, ParallelPerformance.CONTENTRANGE);
        B = r.Next(-ParallelPerformance.CONTENTRANGE, ParallelPerformance.CONTENTRANGE);
        C = r.Next(-ParallelPerformance.CONTENTRANGE, ParallelPerformance.CONTENTRANGE);
        A1 = r.NextDouble();
        B1 = r.NextDouble();
        C1 = r.NextDouble();

        int guidCount = r.Next(ParallelPerformance.GUIDMINCOUNT, ParallelPerformance.GUIDMAXCOUNT);
        for (int i = 0; i < guidCount; i++)
        {
          Guids.Add(Guid.NewGuid());
        }

        int count = r.Next(ParallelPerformance.LINEITEMRESULTMINCOUNT, ParallelPerformance.LINEITEMRESULTMAXCOUNT);
        for (int i = 0; i < count; i++)
        {
          Lines.Add(new LineMathematics.Line(r));
        }

      }


      public int A { get; set; }
      public int B { get; set; }
      public int C { get; set; }

      public double A1 { get; set; }
      public double B1 { get; set; }
      public double C1 { get; set; }

      public List<Guid> Guids { get; set; } = new List<Guid>();

      public List<LineMathematics.Line> Lines { get; set; } = new List<LineMathematics.Line>();

    }

  }

  namespace LineMathematics
  {
    class Line
    {
      public Line() { }

      public Line(Random r)
      {
        Id = Guid.NewGuid();

        int count = r.Next(ParallelPerformance.SEGMENTMINCOUNT, ParallelPerformance.SEGMENTMAXCOUNT);
        for (int i = 0; i < count; i++)
        {
          Segments.Add(new Segment(r));
        }
      }

      static byte[] WriteSegmentList(List<Segment> segments)
      {
        MemoryStream memory = new MemoryStream();
        BinaryWriter writer = new BinaryWriter(memory);

        writer.Write(segments.Count);
        foreach (var lineSegment in segments)
        {
          lineSegment.Write(writer);
        }

        return memory.ToArray();
      }

      static List<Segment> ParseLinesList(byte[] data)
      {
        MemoryStream memory = new MemoryStream(data);
        BinaryReader reader = new BinaryReader(memory);
        var count = reader.ReadInt32();
        if (count == 0)
          return new List<Segment>();

        List<Segment> returnList = new List<Segment>();

        for (var i = 1; i <= count - 1; i++)
        {
          Segment loadedSegment = new Segment();
          loadedSegment.Read(reader);
        }

        return returnList;
      }

      public Guid Id { get; set; }

      [XmlIgnore]
      public List<Segment> Segments { get; set; } = new List<Segment>();

      /// <summary>
      /// Test performance with Byte Arrays in parts of the Project
      /// </summary>
      public byte[] SegmentsBinary
      {
        get
        {
          return WriteSegmentList(Segments);
        }
        set
        {
          Segments = ParseLinesList(value);
        }
      }
    }

    class Segment
    {
      public Segment() { }

      public Segment(int i, Point3 s, Point3 e)
      {
        Index = i;
        Start = s;
        End = e;
      }

      public Segment(Random r)
      {
        Index = r.Next();
        Start = new Point3(r);
        End = new Point3(r);
      }

      public void Write(BinaryWriter writer)
      {
        writer.Write(Index);
        Start.Write(writer);
        End.Write(writer);
      }

      public void Read(BinaryReader reader)
      {
        Index = reader.ReadInt32();
        Start = new Point3();
        Start.Read(reader);
        End = new Point3();
        End.Read(reader);
      }

      public int Index { get; set; }
      public Point3 Start { get; set; }
      public Point3 End { get; set; }

    }

    struct Point3
    {
      public Point3(Random r)
      {
        double halfRange = ParallelPerformance.POINTRANGE / 2;
        X = r.NextDouble() * ParallelPerformance.POINTRANGE - halfRange;
        Y = r.NextDouble() * ParallelPerformance.POINTRANGE - halfRange;
        Z = r.NextDouble() * ParallelPerformance.POINTRANGE - halfRange;
      }

      public void Write(BinaryWriter writer)
      {
        writer.Write(X);
        writer.Write(Y);
        writer.Write(Z);
      }

      public void Read(BinaryReader reader)
      {
        X = reader.ReadDouble();
        Y = reader.ReadDouble();
        Z = reader.ReadDouble();
      }

      public double X { get; set; }
      public double Y { get; set; }
      public double Z { get; set; }
    }
  }
}
`

**Comment by Mike-E-angelo** [comment]
WOW @imperiobadgo thank you for the kind words and for the interesting question here.  From the outset, there isn't anything obvious that I can think of specifically about the ExtendedXmlSerializer that would impact the results you are seeing.  Except that perhaps we have never really considered this scenario. :)

Have you tried the same thing with other serializers, by chance?  I would be interested in seeing how they fare.  As for `Parallel` namespace, from what I have read my impression that the gains that are achieved are really for specific scenarios, and sometimes the "gains" are not as much as hoped for, sort of what you are experiencing, actually. 😁

To be a bit clearer, this is not a supported scenario but it's an interesting one.  When we started doing v2 `async/await` was all the rage.  We should have probably put more effort into supporting it but alas we were only able to get synchronous functionality in there.

Please do let me know if you have any additional/further questions around this and I will see if I can assist you. 👍

**Comment by imperiobadgo** [comment]
Thank's for the answer. 
Is the assumption correct that the serializer caches a lot in static variables? Because in an older version the behavior was that the first pass took longer than the following ones.

**Comment by Mike-E-angelo** [comment]
> Other serializers are not really an option because they are either too rigid or slower than the ExtendedXmlSerialiser. So I've not tested them.

You're speaking all the right words here @imperiobadgo.  I'm OK with that line of reasoning. 😊

As for caching, we definitely do this, but instances are not statically stored.  They are rather stored per-`ConfigurationContainer`.  We may use "static" caching but instances/values are stored in `ConditionalWeakTable` so they get GC'd and released if no other instance is holding onto them.

**Comment by imperiobadgo** [comment]
What exactly is being cashed? Object types or the actual objects?
I made another observation: In version 3.2.5 there was a huge runtime difference between the first and subsequent runs. Can you tell me what exactly changed after that and why? I found the following change, but I can't really understand the difference: #437

In this version, i found out that the runtime with parallel tasks was also very good (twice as fast) after the first run.

**Comment by Mike-E-angelo** [comment]
> What exactly is being cashed? Object types or the actual objects?

Both. :)  We use `TypeInfo` and other `MemberInfo` instances as the caching key for various parts of the serialization/deserialization services.  We do not hold onto instances unless references are enabled, and in that case, we store via a dictionary that is weak-referenced to the `IFormatReader` being sent through the graph.  So, once that `IFormatReader` is released, so are all the instances.  Or at least _should_ be. 😇

That's interesting about #437.  It was used to fix #434 but that was only when `EnableReferences` are used.  Are you using this in the tests that you mention with better performance?  The tests provided above do not seem to be using this, so I am unclear on why that would cause a performance difference unless that method is being used somewhere.

**Comment by imperiobadgo** [comment]
You're right, i'm not using `EnableReferences`. But it still makes a big difference. If I change the References class to the old status, I also get the following results with 4 runs each:

1774,3246 ms: Sequential 0
33,9535 ms: Sequential 1
26,7884 ms: Sequential 2
31,4104 ms: Sequential 3

13727,9436 ms: Extracted 0
43,861 ms: Extracted 1
43,8958 ms: Extracted 2
37,4565 ms: Extracted 3

7398,1325 ms: Parallel 0
18,1082 ms: Parallel 1
25,9608 ms: Parallel 2
29,7209 ms: Parallel 3

Changed References class:

```
using ExtendedXmlSerializer.ContentModel.Members;
using ExtendedXmlSerializer.Core.Sources;
using ExtendedXmlSerializer.Core.Specifications;
using ExtendedXmlSerializer.ExtensionModel.Xml;
using ExtendedXmlSerializer.ReflectionModel;
using System.Collections.Immutable;
using System.Reflection;


namespace ExtendedXmlSerializer.ExtensionModel.References
{
	sealed class References : StructureCacheBase<object, ImmutableArray<object>>, IReferences
	{
		readonly ISpecification<TypeInfo> _allow;
		readonly IReferencesPolicy        _policy;
		readonly ITypeMembers             _members;
		readonly IEnumeratorStore         _enumerators;
		readonly IMemberAccessors         _accessors;

		// ReSharper disable once TooManyDependencies
		public References(IContainsCustomSerialization custom, IReferencesPolicy policy, ITypeMembers members,
		                  IEnumeratorStore enumerators, IMemberAccessors accessors)
			: this(AssignedSpecification<TypeInfo>.Default.And(custom.Inverse()), policy, members, enumerators,
			       accessors) {}

		// ReSharper disable once TooManyDependencies
		public References(ISpecification<TypeInfo> allow, IReferencesPolicy policy, ITypeMembers members,
		                  IEnumeratorStore enumerators, IMemberAccessors accessors)
		{
			_allow       = allow;
			_policy      = policy;
			_members     = members;
			_enumerators = enumerators;
			_accessors   = accessors;
		}

		//public ImmutableArray<object> Get(object parameter)
		//	=> new ReferenceWalker(_allow, _policy, _members, _enumerators, _accessors, parameter).Get();

		protected override ImmutableArray<object> Create(object parameter)
		{
			return new ReferenceWalker(_allow, _policy, _members, _enumerators, _accessors, parameter).Get();
		}

	}
}
```

**Comment by Mike-E-angelo** [comment]
AH!  OK correct... brushing off the dust here. :)

References are applied in the case of types that _could_ have recursive references, which have to be checked hence the performance hit as the objects are not cached.

Try applying `sealed` to all of your classes in the test above and you will see better performance as those classes are eliminated as potential candidates.

Outside of that, I am open to suggestions on how we could improve this while still keeping tests passing.  PR is most definitely welcomed if so. 👍

**Comment by Mike-E-angelo** [comment]
We could possibly add a `ConfigurationContainer.ElideReferenceChecking()` (or `ConfigurationContainer.WithoutReferenceChecking()`) which could bypass the reference checking altogether, but this would be dangerous and incompatible with `EnableReferences`.  There is no extension compatibility checking so users would have to read the documentation of this new method and pray they understand the implications.

**Comment by imperiobadgo** [comment]
You are right! If I convert the classes into sealed classes, I get perfect performance results! 😊

291,6189 ms: Sequential 0
35,8574 ms: Sequential 1
39,2728 ms: Sequential 2
38,282 ms: Sequential 3

31,7169 ms: Extracted 0
34,7519 ms: Extracted 1
51,6593 ms: Extracted 2
55,7814 ms: Extracted 3

90,0111 ms: Parallel 0
54,7511 ms: Parallel 1
18,4012 ms: Parallel 2
27,2295 ms: Parallel 3

> ConfigurationContainer.WithoutReferenceChecking()) which could bypass the reference checking altogether, but this would be dangerous and incompatible with EnableReferences. There is no extension compatibility checking so users would have to read the documentation of this new method and pray they understand the implications.

Would be perfect for me, but I agree with you that there should still be some kind of traceable messages in case of wrong use. 😄

**Comment by Mike-E-angelo** [comment]
Alright, I will see if I can get this in there.  I'll be lazy and point to this issue for the documentation. :P

We'll go with `WithoutReferenceChecking`.

**Comment by Mike-E-angelo** [comment]
Alrighty, renamed to `EnableStaticReferenceChecking` and have a sample of how to use it here:
https://github.com/ExtendedXmlSerializer/home/blob/fdae88ba69d4fdc09882aa8156bcc4003ccdec57/test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue511Tests.cs#L10-L16

A build has been deployed for you to test out here:
https://github.com/ExtendedXmlSerializer/home/pull/512#issuecomment-805619787

If that works well for you we can get it deployed out to NuGet next Tuesday, our typical deployment window.

**Comment by imperiobadgo** [comment]
Thank you very much for this great support!!! 
I will test it and then report back with the results.

**Comment by imperiobadgo** [comment]
When I was testing, I very regularly had several threads trying to access the hash set in RecursionAwareContents at the same time:

   at System.Collections.Generic.HashSet`1.SetCapacity(Int32 newSize, Boolean forceNewHashCodes)
   at System.Collections.Generic.HashSet`1.IncreaseCapacity()
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   at System.Collections.Generic.HashSet`1.Add(T item)
   at ExtendedXmlSerializer.ContentModel.Content.RecursionAwareContents.Get(TypeInfo parameter)
   at ExtendedXmlSerializer.ExtensionModel.Types.NullableStructureAwareExtension.NullableStructureAwareContents.Get(TypeInfo parameter)
   at ExtendedXmlSerializer.ExtensionModel.Xml.CustomSerializationExtension.Contents.Get(TypeInfo parameter)
   at ExtendedXmlSerializer.ExtensionModel.Xml.MigrationsExtension.Contents.Get(TypeInfo parameter)
   at ExtendedXmlSerializer.Core.Sources.Cache`2.Create(TKey parameter)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at ExtendedXmlSerializer.Core.Sources.CacheBase`2.Get(TKey key)
   at ExtendedXmlSerializer.ExtensionModel.References.DeferredContents.Get(TypeInfo parameter)
   at ExtendedXmlSerializer.ContentModel.Content.Serializers.Get(TypeInfo parameter)
   at ExtendedXmlSerializer.ExtensionModel.References.ReferenceAwareSerializers.Get(TypeInfo parameter)
   at ExtendedXmlSerializer.ContentModel.Content.DynamicAwareSerializers.Get(TypeInfo parameter)
   at ExtendedXmlSerializer.Core.Sources.Cache`2.Create(TKey parameter)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at ExtendedXmlSerializer.Core.Sources.CacheBase`2.Get(TKey key)
   at ExtendedXmlSerializer.ContentModel.RuntimeSerializers.Get(TypeInfo parameter)
   at ExtendedXmlSerializer.ContentModel.Collections.Collections.Get(TypeInfo parameter)
   at ExtendedXmlSerializer.Core.Sources.ConditionalSource`2.Get(TParameter parameter)
   at ExtendedXmlSerializer.Core.Sources.ConditionalSource`2.Get(TParameter parameter)
   at ExtendedXmlSerializer.Core.Sources.ConditionalSource`2.Get(TParameter parameter)
   at ExtendedXmlSerializer.Core.Sources.ConditionalSource`2.Get(TParameter parameter)
   at ExtendedXmlSerializer.Core.Sources.ConditionalSource`2.Get(TParameter parameter)
   at ExtendedXmlSerializer.Core.Sources.ConditionalSource`2.Get(TParameter parameter)
   at ExtendedXmlSerializer.Core.Sources.ConditionalSource`2.Get(TParameter parameter)
   at ExtendedXmlSerializer.Core.Sources.ConditionalSource`2.Get(TParameter parameter)
   at ExtendedXmlSerializer.ContentModel.Content.RecursionAwareContents.Get(TypeInfo parameter)
   at ExtendedXmlSerializer.ExtensionModel.Types.NullableStructureAwareExtension.NullableStructureAwareContents.Get(TypeInfo parameter)
   at ExtendedXmlSerializer.ExtensionModel.Xml.CustomSerializationExtension.Contents.Get(TypeInfo parameter)
   at ExtendedXmlSerializer.ExtensionModel.Xml.MigrationsExtension.Contents.Get(TypeInfo parameter)
   at ExtendedXmlSerializer.Core.Sources.Cache`2.Create(TKey parameter)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at ExtendedXmlSerializer.Core.Sources.CacheBase`2.Get(TKey key)
   at ExtendedXmlSerializer.ExtensionModel.References.DeferredContents.Get(TypeInfo parameter)
   at ExtendedXmlSerializer.ContentModel.Members.VariableTypeMemberContents.Get(IMember parameter)
   at ExtendedXmlSerializer.Core.Sources.ConditionalSource`2.Get(TParameter parameter)
   at ExtendedXmlSerializer.Core.Sources.DecoratedSource`2.Get(TParameter parameter)
   at ExtendedXmlSerializer.Core.Sources.ConditionalSource`2.Get(TParameter parameter)
   at ExtendedXmlSerializer.Core.Sources.DecoratedSource`2.Get(TParameter parameter)
   at ExtendedXmlSerializer.ExtensionModel.Content.Members.AlteredMemberContents.Get(IMember parameter)
   at ExtendedXmlSerializer.ContentModel.Members.MemberSerializers.Content(IMember profile, IMemberAccess access)
   at ExtendedXmlSerializer.ContentModel.Members.MemberSerializers.Get(IMember parameter)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ExtendedXmlSerializer.ContentModel.Members.MemberSerializations.Create(TypeInfo parameter)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at ExtendedXmlSerializer.Core.Sources.CacheBase`2.Get(TKey key)
   at ExtendedXmlSerializer.ContentModel.Members.InstanceMemberSerializations.Get(TypeInfo parameter)
   at ExtendedXmlSerializer.ContentModel.Members.MemberedContents.Get(TypeInfo parameter)
   at ExtendedXmlSerializer.Core.Sources.ConditionalSource`2.Get(TParameter parameter)
   at ExtendedXmlSerializer.Core.Sources.ConditionalSource`2.Get(TParameter parameter)
   at ExtendedXmlSerializer.Core.Sources.ConditionalSource`2.Get(TParameter parameter)
   at ExtendedXmlSerializer.Core.Sources.ConditionalSource`2.Get(TParameter parameter)
   at ExtendedXmlSerializer.Core.Sources.ConditionalSource`2.Get(TParameter parameter)
   at ExtendedXmlSerializer.Core.Sources.ConditionalSource`2.Get(TParameter parameter)
   at ExtendedXmlSerializer.Core.Sources.ConditionalSource`2.Get(TParameter parameter)
   at ExtendedXmlSerializer.Core.Sources.ConditionalSource`2.Get(TParameter parameter)
   at ExtendedXmlSerializer.Core.Sources.ConditionalSource`2.Get(TParameter parameter)
   at ExtendedXmlSerializer.ContentModel.Content.RecursionAwareContents.Get(TypeInfo parameter)
   at ExtendedXmlSerializer.ExtensionModel.Types.NullableStructureAwareExtension.NullableStructureAwareContents.Get(TypeInfo parameter)
   at ExtendedXmlSerializer.ExtensionModel.Xml.CustomSerializationExtension.Contents.Get(TypeInfo parameter)
   at ExtendedXmlSerializer.ExtensionModel.Xml.MigrationsExtension.Contents.Get(TypeInfo parameter)
   at ExtendedXmlSerializer.Core.Sources.Cache`2.Create(TKey parameter)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at ExtendedXmlSerializer.Core.Sources.CacheBase`2.Get(TKey key)
   at ExtendedXmlSerializer.ExtensionModel.References.DeferredContents.Get(TypeInfo parameter)
   at ExtendedXmlSerializer.ContentModel.Content.Serializers.Get(TypeInfo parameter)
   at ExtendedXmlSerializer.ExtensionModel.References.ReferenceAwareSerializers.Get(TypeInfo parameter)
   at ExtendedXmlSerializer.ContentModel.Content.DynamicAwareSerializers.Get(TypeInfo parameter)
   at ExtendedXmlSerializer.Core.Sources.Cache`2.Create(TKey parameter)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at ExtendedXmlSerializer.Core.Sources.CacheBase`2.Get(TKey key)
   at ExtendedXmlSerializer.ExtensionModel.Xml.Write.Execute(Writing parameter)
   at ExtendedXmlSerializer.ExtensionModel.Xml.Serializer.Serialize(XmlWriter writer, Object instance)
   at ExtendedXmlSerializer.ExtensionModel.Xml.ExtendedXmlSerializer.Serialize(XmlWriter writer, Object instance)
   at ExtendedXmlSerializer.ExtensionModel.Xml.InstanceFormatter.Get(Object parameter)
   at ExtendedXmlSerializer.ExtensionMethodsForSerialization.Serialize(IExtendedXmlSerializer this, XmlWriterSettings settings, Object instance)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()

**Comment by imperiobadgo** [comment]
I would suggest this following change:

```
using System.Collections.Generic;
using System.Reflection;

namespace ExtendedXmlSerializer.ContentModel.Content
{
	sealed class RecursionAwareContents : IContents
	{
    private object _lockObject;
    readonly IContents _contents;
    readonly ISet<TypeInfo> _types;

    public RecursionAwareContents(IContents contents) : this(contents, new HashSet<TypeInfo>()) { }

    public RecursionAwareContents(IContents contents, ISet<TypeInfo> types)
    {
      _lockObject = new object();
      _contents = contents;
      _types = types;
    }

    public ISerializer Get(TypeInfo parameter)
    {
      ISerializer result = null;
      lock (_lockObject)
      {
        result = _types.Add(parameter)
                     ? _contents.Get(parameter)
                     : new DeferredSerializer(_contents.Build(parameter));
        _types.Remove(parameter);
      }
      return result;
    }
  }
}
```

Could you make the change in the preview so that I can test whether this no longer occurs in my software?
It is quite difficult to provoke this error with the test classes, although I have managed to do this a few times. But this error occurs very regularly in my software...

**Comment by Mike-E-angelo** [comment]
Yeah that's a good point, we do have the `new ConfigurationContainer().EnableThreadProtection()` method but that locks the entire instance, so I am not sure of the benefit in a `Parallel` scenario.  Currently we have no `lock` usages due to performance considerations.  However, we might be able to configure the `ISet<TypeInfo>` used.  Let me look into that.

**Comment by imperiobadgo** [comment]
> Yeah that's a good point, we do have the new ConfigurationContainer().EnableThreadProtection() method but that locks the entire instance, so I am not sure of the benefit in a Parallel scenario.

I have also observed this. How often are hashsets used otherwise?

**Comment by Mike-E-angelo** [comment]
> I have also observed this. How often are hashsets used otherwise?

Good question.  I believe that is the only place we're storing state like that.  I'd rather find a way not to do that as well as I am not a fan of it.

Regardless, I've added a new call `EnableThreadAwareRecursionContent` which you can see demonstrated here:
https://github.com/ExtendedXmlSerializer/home/blob/f7a61b878322146ab4b393676a4070cf53ccadf6/test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue513Tests.cs#L10-L16

The build is here for your review:
https://github.com/ExtendedXmlSerializer/home/pull/514#issuecomment-806059716

Interestingly enough, I just today ran into this very problem [with my own project](https://starbeam.one/), so I'm doing both of us a favor here. 😅

**Comment by imperiobadgo** [comment]
Thanks, I'll test it right away! 😅

**Comment by imperiobadgo** [comment]
It just seems to work perfectly! Do you have a link for the design pattern, like the structure of the ExtendedXmlSerializer? I would be very interested to finally understand the processes in the background of the serialiser.

**Comment by Mike-E-angelo** [comment]
> It just seems to work perfectly! 

Very glad to hear this. 😁

> Do you have a link for the design pattern, like the structure of the ExtendedXmlSerializer?

Oh man, not really.  I mean, there is one pattern I use extensively in all my development, and that is [the decorator pattern](https://en.wikipedia.org/wiki/Decorator_pattern).  FWIW, before I joined in with ExtendedXmlSerializer v2, I was working on a framework that had a lot of these key concepts, then I pared it down tremendously for ExtendedXmlSerializer (sorta like a mini-framework).  But, there were so many additions/changes that I incorporated them back into my framework.  The results you can see here, if interested:
https://github.com/DragonSpark/Framework

With the active branch being here (the product I mentioned earlier):
https://github.com/DragonSpark/Framework/tree/projects/Starbeam

I am still very much decorator pattern all the way.  I would say easily 90% if not more of my code is decorator.  It really allows you to do so much by way of manageable design and keeping the chaos in front of you.  In fact I used it all for the `EnableThreadAwareRecursionContent` solution if you want to poke around.  

It's basically taking a core solution and then wrapping another around it that modifies it in some way.  Case in point:

https://github.com/ExtendedXmlSerializer/home/blob/f7a61b878322146ab4b393676a4070cf53ccadf6/src/ExtendedXmlSerializer/ExtensionModel/ThreadAwareRecursionContentExtension.cs#L28-L41

:)

**Comment by imperiobadgo** [comment]
Thank's again for your help! I will take a look at the links.

**Comment by Mike-E-angelo** [comment]
Alrighty, this has been posted to the main package on NuGet:
https://www.nuget.org/packages/ExtendedXmlSerializer/

Appreciate the efforts here to look into performance.  True story: when we first started it was a core focus, but then I got really caught up in performance anomalies that turned out to be JIT loop alignment issues.  It drove me absolutely crazy and actually almost burned me out.  Totally crazy stuff.  Basically one run would report a particular result, and then simply changing an attribute or line of code that had nothing to do with the system under test would produce a result 10-15% difference.  It ended me up in the boiler room of .NET engineering:
https://github.com/dotnet/runtime/issues/4584#issuecomment-392554011

I was ready to pull my freaking hair out.  Or remove my head altogether. :P  After that (it was like a 3 week ordeal) I reluctantly decided to not put so much focus on performance.

Good news is that they are finally looking into the jitness:
https://devblogs.microsoft.com/dotnet/loop-alignment-in-net-6/

Anyways, _this_ issue has been addressed.  Please do let me know of any further problems you run into and I will see if I can address them.  Closing for now.
