### ISSUE TITLE
Deserialization using ".WithUnknownContent().Continue()" still silently aborts on unknown content.

### ISSUE THREAD

**Issue by rummelsworth** [ExtendedXmlSerializer/home#521]
Some code to repro:

```C#
    public class Test
    {
        public int Value1 { get; set; }
        //public Item Item1 { get; set; }
        public int Value2 { get; set; }
        //public List<int> Items2 { get; set; }
        public int Value3 { get; set; }
        //public List<Item> Items3 { get; set; }
        public int Value4 { get; set; }
    }

    public class Item
    {
        public int Value { get; set; }
    }

    class Program
    {
        static void Main()
        {
            const string inputXml =
@"<?xml version=""1.0"" encoding=""utf-8""?>
<Test xmlns=""clr-namespace:ExsDeserializationIssue;assembly=ExsDeserializationIssue"">
  <Value1>11</Value1>
  <Item1>
    <Value>1</Value>
  </Item1>
  <Value2>22</Value2>
  <Items2>
    <Capacity>4</Capacity>
    <int xmlns=""https://extendedxmlserializer.github.io/system"">1</int>
    <int xmlns=""https://extendedxmlserializer.github.io/system"">2</int>
    <int xmlns=""https://extendedxmlserializer.github.io/system"">3</int>
  </Items2>
  <Value3>33</Value3>
  <Items3>
    <Capacity>4</Capacity>
    <Item>
      <Value>1</Value>
    </Item>
    <Item>
      <Value>2</Value>
    </Item>
    <Item>
      <Value>3</Value>
    </Item>
  </Items3>
  <Value4>44</Value4>
</Test>";

            var s = new ConfigurationContainer()
                .WithUnknownContent()
                .Continue()
                //.Call(_ => Console.WriteLine("Unknown content: " + _.Name))
                .Create();

            var output = s.Deserialize<Test>(inputXml);
            Console.WriteLine(output.Value1); // 11
            Console.WriteLine(output.Value2); // 0 but should be 22
            Console.WriteLine(output.Value3); // 0 but should be 33
            Console.WriteLine(output.Value4); // 0 but should be 44

            // --- Below is the code that generates the input XML when the "Items" lists are uncommented.

            //var t = new Test
            //{
            //    Value1 = 11,
            //    Value2 = 22,
            //    Value3 = 33,
            //    Value4 = 44,
            //    Item1 = new() { Value = 1 },
            //    Items2 = new()
            //    {
            //        1,
            //        2,
            //        3,
            //    },
            //    Items3 = new()
            //    {
            //        new() { Value = 1 },
            //        new() { Value = 2 },
            //        new() { Value = 3 },
            //    }
            //};

            //var outputXml = s.Serialize(new XmlWriterSettings() { Indent = true }, t);
            //Console.WriteLine(outputXml);
        }
    }
```

Also, when `Call` is used instead of `Continue`, the delegate is only invoked for "Item1".

For what it's worth, I think I can see `Continue` partially working when deserializing my real XML, which is _much_ larger. It makes it past a few elements for which there's no matching property, then it inexplicably fails (i.e. silently aborts) when it reaches a certain unknown element. I've tried to figure out a pattern to what finally triggers the silent failure, but I can't get quite the same behavior in simpler setups, including the repro here. Regardless, this repro does seem to show `Continue` misbehaving. Or am I missing something?

**Comment by Mike-E-angelo** [comment]
Thank you for reporting this @rummelsworth.  Looks like this is an issue with unknown complex content, or uknown content with additional content under it.  I will see if I can get this to essentially return to the current indent index before continuing to read content.

**Comment by Mike-E-angelo** [comment]
Alright @rummelsworth check out the following when you can to see if it treats you better:
https://github.com/ExtendedXmlSerializer/home/pull/522#issuecomment-843831615

As for the issue you are experiencing with `WithUnknownContent.Call`, it too will have to account for complex content as well, calling [`XmlReader.Skip`](https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmlreader.skip?view=net-5.0) until the desired depth is attained.  You can view [this file](https://github.com/ExtendedXmlSerializer/home/blob/09a649849529d0ae42147cf84b16776f8e402833/src/ExtendedXmlSerializer/ExtensionModel/Content/ContinueOnUnknownContent.cs) for reference.

Please do let me know if you encounter any further/additional issues and I will do my best to assist you. 👍

**Comment by Mike-E-angelo** [comment]
This fix has been deployed to NuGet:
https://www.nuget.org/packages/ExtendedXmlSerializer/

Please do let me know if you encounter any issues around this and we can take it from there.  Closing for now.

**Comment by rummelsworth** [comment]
@Mike-E-angelo Sorry for not following up earlier. I hadn't gotten around to trying it at that time due to a weirdness with nuget and installing the preview build, then I ended up figuring out what I was doing wrong in my original use of XmlSerializer (which had prompted me to investigate this package). After plunging ahead, I forgot to come back and try this out to confirm the fix on my end. Anyway, I appreciate your super-quick response and resolution on this issue! Truly impressive. Thanks.

**Comment by Mike-E-angelo** [comment]
No worries @rummelsworth!  I am glad it is working for you and we got this squared away. 👍
