### ISSUE TITLE
Dictionary causing problems

### ISSUE THREAD

**Issue by Trhac** [ExtendedXmlSerializer/home#528]
Hello, 

in my project I need to store data in Dictionary<string,object>. I know this isn't the best idea ever, but that is the API I got. When I try to serialize class containing this dictionary and also a list of some other class, I get a NullReferenceException - Object reference not set to an instance of an object. 

Here's a small class to demonstrate the issue.

```c#
private static void MinimalSerializerTest()
{
    var c = new ClassWithDictionary();
    c.Dict.Add("key",123);

    var configuration = new ConfigurationContainer();
    var serializer = configuration.Create();
    string path = "Data/projekt.xml";

    var serialized = serializer.Serialize(c);
    File.WriteAllText(path, serialized);

    var deserialized = File.ReadAllText(path);
    var loadedProject = serializer.Deserialize<ClassWithDictionary>(deserialized);
}

public class ClassWithDictionary
{
    public ClassWithDictionary()
    {
        Dict = new Dictionary<string, object>();

        ListWithItems = new List<ClassWithProperty>();
        ListWithItems.Add(new ClassWithProperty());        
    }

    public Dictionary<string,object> Dict { get; set; }

    public IList<ClassWithProperty> ListWithItems { get; set; }
}

public class ClassWithProperty
{
    public string Text { get; set; }
}
```

I sincerely hope that there is a quick fix for this issue.

Thanks,
Jakub

**Comment by Mike-E-angelo** [comment]
The fix for this has been published to NuGet:
https://www.nuget.org/packages/ExtendedXmlSerializer/

Please do let me know if you encounter any additional issues by opening a new ticket and we'll take it from there.  Closing this issue for now.
