### ISSUE TITLE
Serializing empty lists

### ISSUE THREAD

**Issue by imperiobadgo** [ExtendedXmlSerializer/home#530]
Thanks again for this great tool!

I noticed that the serializer treats empty lists the same as unassigned ones (containing null). In both cases, null is written to the property at desirialization. 
Is this an intended behavior? 
Is it possible to change this behavior by adjusting the configuration?

**Comment by Mike-E-angelo** [comment]
This fix has been deployed to NuGet:
https://www.nuget.org/packages/ExtendedXmlSerializer/

If you encounter any further issues please open a new issue and we'll take it from there.  Closing this for now.

**Comment by imperiobadgo** [comment]
I've only just managed to test your changes. But they work perfectly as expected! Thanks again!

**Comment by Mike-E-angelo** [comment]
Woohoo... glad to hear @imperiobadgo.  Thank you for the confirmation. 👍
