### ISSUE TITLE
How to use converters for nullable types

### ISSUE THREAD

**Issue by zvikara** [ExtendedXmlSerializer/home#532]
I have a backward compatibility requirement to serialize all enums and booleans as integer values.
So I need my xml to contain
```xml
<STATUS>1</STATUS>
<COMPLETED>1</COMPLETED>
```
instead of
```xml
<STATUS>Ok</STATUS>
<COMPLETED>true</COMPLETED>
```
Specifically I use nullable enum an boolean types in my entities.

I got it to work by registering IConverters for <int?> and <bool?>

```c#
       private static IExtendedXmlSerializer CreateSerializer(string root) => new ConfigurationContainer()
            .EnableImplicitTyping(implicitTypes)
            .Type<T>().Name(root)
            .Type<int?>().Register().Converter().Using(NullableIntConverter.Default)
            .Type<bool?>().Register().Converter().Using(NullableBoolConverter.Default)
            .EnableThreadProtection()
            .Create();

        private class NullableIntConverter : IConverter<int?>
        {
            public static readonly NullableIntConverter Default = new NullableIntConverter();

            public bool IsSatisfiedBy(TypeInfo parameter)
                => parameter.AsType() == typeof(int?);

            public int? Parse(string data)
                => string.IsNullOrEmpty(data) ? (int?)null : int.Parse(data);

            public string Format(int? instance)
                => instance?.ToString();
        }

        private class NullableBoolConverter : IConverter<bool?>
        {
            public static readonly NullableBoolConverter Default = new();

            public bool IsSatisfiedBy(TypeInfo parameter)
                => parameter.AsType() == typeof(bool?);

            public bool? Parse(string data) => data switch
            {
                "0" => false,
                "1" => true,
                _ => null
            };
```

This is working for me with version 3.4.2 but stopped working in version 3.4.3
My guess that with the introduction of nullable types support, the converters are not overriding the default serialization.

Is there a workaround? I thought about using ISerializerExtension or IAlteration but couldn't figure how to use those APIs.

**Comment by Mike-E-angelo** [comment]
DOH... sorry for breaking your code @zvikara and thank you for making me aware of this.  We should indeed be checking for registered converters.  Please check out this build and see if it treats you better:

https://github.com/ExtendedXmlSerializer/home/pull/534#issuecomment-907775464

Let me know if you have any further issues and I will look into them for you. 👍

**Comment by zvikara** [comment]
Thanks very much for the very quick response!!!
I tested the fix with my code and it works!

**Comment by Mike-E-angelo** [comment]
Great, @zvikara!  I will get this deployed to NuGet on Tuesday and will update here when it's ready.  Please feel free to use the preview build until then.

**Comment by Mike-E-angelo** [comment]
This has been deployed to NuGet:
https://www.nuget.org/packages/ExtendedXmlSerializer/

Thank you for taking the time to report this and improving ExtendedXmlSerializer. 👍
