### ISSUE TITLE
Support for Azure Functions

### ISSUE THREAD

**Issue by ChristopherL-STCU** [ExtendedXmlSerializer/home#543]
When I try using this in an Azure Function I receive the error:

> System.Private.CoreLib: Exception while executing function: MyTestClass. ExtendedXmlSerializer: Unable to load DLL 'fusion.dll' or one of its dependencies: The specified module could not be found. (0x8007007E).

Here's my sample code:
```
var serializer = new ConfigurationContainer()
    .EnableImplicitTyping(typeof(MyTestClass))
    .Create();
serializer.Serialize(new MyTestClass { MyProperty = 1 })
```

```
public class MyTestClass
{
    public int MyProperty { get; set; }
}
```

Is it possible for me to configure `ExtendedXmlSerializer` to be used with Azure Functions or is it possible for the library to be updated to be usable in an Azure Function?

**Comment by Mike-E-angelo** [comment]
Hey there @ChristopherL-STCU thank you for writing in with this question.  I am glad to see that I am not the only one with struggles around Azure Functions. 😁  In fact, I encountered them so much I ended up using WebJobs as much as I could in its stead.

In any case, are you able to confirm if this occurs if you remove all ExtendedXmlSerializer code?  If so, I would start putting Information outputs (logging) around the lines to see where exactly this is failing.  I am unaware of what `fusion.dll` is, but apparently, [it has some history with this error](https://github.com/Azure/azure-sdk-for-net/issues/4010).

**Comment by ChristopherL-STCU** [comment]
Thanks @Mike-E-angelo. The error only occurs when I add `ExtendedXmlSerializer`. I noticed the GitHub issue you referenced when I was trying to figure it out as well. I also see [`fusion.dll` is used by `ExtendedXmlSerializer`](https://github.com/ExtendedXmlSerializer/home/blob/master/src/ExtendedXmlSerializer/ReflectionModel/AssemblyPath.cs#L40). I wonder if `fusion.dll` is not available from within the Azure Function context. Azure Functions are particular. I don't know much about `fusion.dll` either and so I don't know if this should work within an Azure Function or if a different approach is needed for Azure Functions. It may not be worthwhile to try to figure all of this out, but I thought I'd ask the question here.

**Comment by Mike-E-angelo** [comment]
WOW... first off, thank you for having more interest in this area than I do, @ChristopherL-STCU. 😆  I appreciate you digging through and finding the culprit.  I was pretty amazed that we indeed had a dependency on this dll, and even more amazed that it somehow works cross-platform.

I believe that was added eons ago before there was a `netstandard2.0` call to `Assembly.Load/LoadWithPartialName`.

I have updated the usage of this, and a build is here for you to check out:
https://github.com/ExtendedXmlSerializer/home/pull/544#issuecomment-909639753

Please let me know if you run into any further issues and I will take a look into it for you. 👍

**Comment by Mike-E-angelo** [comment]
Doh I may have mispoken here, @ChristopherL-STCU ... the logic appears to be related to #366 and is intended to retrieve from the GAC.

Can you confirm that you are using Azure Functions in .NETCore or .NET Framework?  And which version?

**Comment by Mike-E-angelo** [comment]
Hi @ChristopherL-STCU if you are using .NET Core please try this build out:
https://github.com/ExtendedXmlSerializer/home/pull/544#issuecomment-909665170

If you are running .NET Framework then I am out of ideas.  That `fusion.dll` is a very native assembly and should be located for .NET Framework scenarios.  I cannot remove it as it is necessary for scenarios such as #366 where the GAC has an assembly that is not found on local disk.  As such, I have basically modified the build so that the GAC-accessing logic is only emitted for the .NET Framework libraries.  Hopefully that addresses the issue here, but who knows with Azure Functions. 😓

**Comment by ChristopherL-STCU** [comment]
Wow! Thanks for making the change so quickly!

It is using .Net Core, `<TargetFramework>netcoreapp3.1</TargetFramework>`. I grabbed the preview version you just built but I'm still experiencing the error. 😕 I decompiled the assembly and I do have the change you made. I'm not sure what's up. I'll continue to experiment and report back if I make any progress.

**Comment by Mike-E-angelo** [comment]
Whoa so you are saying you can verify that the link to `fusion.dll` is removed and you're still getting a `fusion.dll` error?  That is wild.  It must be a caching issue.  Does this occur locally or deployed?

**Comment by ChristopherL-STCU** [comment]
The problem appears to be because there is a hyphen in my project name, and so there is a hyphen in the generated assembly name. [The ExtendedXmlSerializer assembly parser does not include hyphen as a valid character](https://github.com/ExtendedXmlSerializer/home/blob/issues/fix/i543/src/ExtendedXmlSerializer/ContentModel/Reflection/AssemblyPathParser.cs#L11) when parsing the assembly name. This mean when ExtendedXmlSerializer tries to load the assembly it's only using a partial name of the assemble, and therefore cannot find it. This causes ExtendedXmlSerializer to fallback to the old assembly load method which uses `fusion.dll`, hence the error message I'm experiencing.

**Comment by Mike-E-angelo** [comment]
Excellent work in tracking this down, @ChristopherL-STCU.  I am going to undo the work yesterday as I absolutely detest compiler definitions which is what I was using to make that work.

Please try this build which allows hyphens as allowed characters in assembly names and let me know if it treats you any better:
https://github.com/ExtendedXmlSerializer/home/pull/544#issuecomment-910798800

**Comment by ChristopherL-STCU** [comment]
Yes, that works for me! 🎉 Thanks! ❤️

**Comment by Mike-E-angelo** [comment]
Awesome!  Release days are typically on Tuesdays so I will get this launched out next Tuesday.  Please feel free to use the preview build until then and I will update here once it's deployed to NuGet. 👍

**Comment by Mike-E-angelo** [comment]
This has been deployed to NuGet:
https://www.nuget.org/packages/ExtendedXmlSerializer/

Please do let me know if you encounter any additional/further issues and I will look into them for you.

Closing this for now.

**Comment by SuperJMN** [comment]
Ouch. I've tried every package in that thread, but no dice.
