### ISSUE TITLE
EnableImplicitTyping problem caused by issue #528

### ISSUE THREAD

**Issue by Trhac** [ExtendedXmlSerializer/home#545]
Hello,

sorry for late reply, I had some problems with reproducing this issue. This is a new problem caused by your fix for [Issue 528](https://github.com/ExtendedXmlSerializer/home/issues/528).

Combining implicit and explicit types leads to deserialization problem. Please see the attached solution.

[SerializerTestsWithoutNamespaces.zip](https://github.com/ExtendedXmlSerializer/home/files/7091132/SerializerTestsWithoutNamespaces.zip)

Thanks,
Jakub

**Comment by Mike-E-angelo** [comment]
Doh... thank you for reporting this @Trhac.  Can you post the code to a repository, by chance?  It is far more preferred to a zip file.

**Comment by Mike-E-angelo** [comment]
Actually @Trhac I was able to reproduce this simply by adding `EnableImplicitTyping` onto the test for #528.

Looking into this now.

**Comment by Mike-E-angelo** [comment]
Alright @Trhac please try the following build:
https://github.com/ExtendedXmlSerializer/home/pull/546#issuecomment-910338669

If everything looks OK to you I will send this out probably in the next day or so as this might be an impacting change that others will be running into with `3.7.3`

**Comment by Trhac** [comment]
Thanks Mike, your fix works great! So far no problems. Thank you.

**Comment by Mike-E-angelo** [comment]
Woohoo... OK I am going to send this out ASAP.  Thank you for verifying, @Trhac!
