### ISSUE TITLE
NullReferenceException with UseAutoFormatting and nullable Structs

### ISSUE THREAD

**Issue by imperiobadgo** [ExtendedXmlSerializer/home#550]
Hello again ;)

I found a problem with the changes #531 regarding UseAutoFormatting after all. Nullable structs cannot be serialized. Here is my example code:

```
public static void Main(string[] args)
{

  var configuration = new ConfigurationContainer();
  configuration.UseAutoFormatting();
  var entry = new Subject();
  entry.Struct = new ItemStruct();

  var serializer = configuration.Create();
  var serialized = serializer.Serialize(entry);
  var deserialized = serializer.Deserialize<Subject>(serialized);
}

class Subject
{

  public ItemStruct? Struct;

}
struct ItemStruct
{}
```

**Comment by Mike-E-angelo** [comment]
Hah! No worries @imperiobadgo I very much appreciate you taking the time to make sure this sucker works as intended.  It's a bit daunting to see others use it so I want to make sure it doesn't break.

I was so focused on getting `UseAutoFormatting` to work with converters that I forgot to account for when a converter doesn't exist for a struct. 😥

I have a new build for you to test here:
https://github.com/ExtendedXmlSerializer/home/pull/551#issuecomment-913618153

If that works for you I will get this out in tomorrow's release. 👍

**Comment by imperiobadgo** [comment]
Thanks for the quick reply as always. Your solution works perfectly!

**Comment by Mike-E-angelo** [comment]
This has been published to NuGet:
https://www.nuget.org/packages/ExtendedXmlSerializer/

Thank you again for all your reports and efforts towards improving ExtendedXmlSerializer. 👍
