### ISSUE TITLE
ArgumentException Stream was not readable.

### ISSUE THREAD

**Issue by fairking** [ExtendedXmlSerializer/home#573]
I have the following example:
``` c#
    public static class XmlSerializerHelper
    {
        public static void Serialize<T>(this T obj, string destPath)
        {
            var xmlSerializer = new ConfigurationContainer()
                .UseAutoFormatting()
                .UseOptimizedNamespaces()
                .EnableImplicitTyping(typeof(T))
                // Additional configurations...
                .Create();

            using (var fileStream = new FileStream(destPath, FileMode.Create, FileAccess.Write))
            {
                xmlSerializer.Serialize(fileStream, obj);
            }
        }
    }
```

And it throws the follwing error:
```
System.ArgumentException
  HResult=0x80070057
  Message=Stream was not readable.
  Source=System.Private.CoreLib
  StackTrace:
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at System.IO.StreamReader..ctor(Stream stream)
   at ExtendedXmlSerializer.ExtensionModel.Xml.InstanceFormatter.Get(Object parameter)
   at ExtendedXmlSerializer.ExtensionMethodsForSerialization.Serialize(IExtendedXmlSerializer this, IXmlWriterFactory factory, Func`1 stream, Object instance)
   at ExtendedXmlSerializer.ExtensionMethodsForSerialization.Serialize(IExtendedXmlSerializer this, Stream stream, Object instance)
   at ParcelTest.Helpers.XmlSerializerHelper.Serialize[T](T obj, String destPath) in C:\Code\parcel-test\ParcelTest\Helpers\XmlSerializerHelper.cs:line 34
   at ParcelTest.Program.Main(String[] args) in C:\Code\parcel-test\ParcelTest\Program.cs:line 16
```

Any idea why it's happening?

**Comment by fairking** [comment]
Also I cannot understand why the method returns `string`. In case on a huge amount of data I thought the stream allows to write all data gradually without increasing memory pool.

**Comment by Mike-E-angelo** [comment]
Hi @fairking thank you for writing in with your question here.  I will see if I can assist.

> Any idea why it's happening?

Indeed, it is related to your second concern here:

> Also I cannot understand why the method returns string.

You are actually calling a convenience extension method that we use extensively to forego the use of streams.  If you would like to use a custom stream, try making use of the `XmlWriter.Create` method:

```
using (var fileStream = new FileStream(destPath, FileMode.Create, FileAccess.Write))
{
	using (var writer = XmlWriter.Create(fileStream))
	{
		xmlSerializer.Serialize(writer, obj);
	}
}
```

That _should_ get you closer to the results/experience that you are looking for... if you do have any further problems let me know and I will see if I get it answered for you. 👍

**Comment by Mike-E-angelo** [comment]
FWIW @fairking here is the contract the `xmlSerializer` variable in the code you provided implements:

https://github.com/ExtendedXmlSerializer/home/blob/master/src/ExtendedXmlSerializer/ExtensionModel/Xml/ISerializer.cs

Note the use of `System.Xml.XmlWriter` and `System.Xml.XmlReader`, the same that the traditional `XmlSerializer` uses.

**Comment by Mike-E-angelo** [comment]
Looks like this issue was answered, and will close for now.  If you do have any further questions please do leave a comment and we can take it from there.
