### ISSUE TITLE
Serialized string dropped

### ISSUE THREAD

**Issue by CipValOut** [ExtendedXmlSerializer/home#575]
Hi,

I am trying to serialize data from my function, then data to be cached (due a formatting problem inside code tag I attach the code)

the not expecting behavior is the the serialized string is dropped, see attachment. Using AutoFormatter and Optimized options the string is shorter.

I have no errors serializing on debug, how can I help to track this issue?

[serializeOutput.txt](https://github.com/ExtendedXmlSerializer/home/files/8677224/serializeOutput.txt)
[code.txt](https://github.com/ExtendedXmlSerializer/home/files/8677262/code.txt)

**Comment by Mike-E-angelo** [comment]
Hi @CipValOut thank you for reporting this.  Are you able to see this problem without the Azure/Telerik components?  If you are able to provide a simple (or simpler 😁) reproduction I can take a look into this for you.

**Comment by CipValOut** [comment]
hi @Mike-E-angelo , 

I tried without success, I tried to rewrite with custom class like the telerik and azure but I had to give up.
I changed my code, removig Ref I didn't used the Serialize anymore.
I had to recode but I solved.

Thx

**Comment by Mike-E-angelo** [comment]
OK @CipValOut thank you for the update.  If you encounter any further issues/problems please feel free to open a new issue and I can see if I can assist you. 👍
