### ISSUE TITLE
Is it possible to use the namespace optimizer on its own with standard .net fx xml attributes

### ISSUE THREAD

**Issue by alexf2017** [ExtendedXmlSerializer/home#582]
Hi, 
I have types with standard xml attributes defining the namespaces and attributes and would like to get them outputted in the result document. I can't find a way to force your library to use those attributes. Is that possible somehow?

Thanks

**Comment by Mike-E-angelo** [comment]
Hi @alexf2017 thank you for writing in and for your question.  If the document is being read into memory to instantiate a CLR object graph, when it is written out as a resulting XML document all attributes will be preserved accordingly w/ ExtendedXmlSerializer's own devices.  I am not sure if there is a way to preserve 1:1 of the input document's namespaces.

Note that ExtendedXmlSerializer's primary use case is the above.  That is, it is primarily designed to create and persist .NET object graphs.  Anything else is "maybe" supported, but there are limitations:

https://github.com/ExtendedXmlSerializer/home#known-issues
https://github.com/ExtendedXmlSerializer/home/wiki/FAQs#systemxmlserializer-vs-extendedxmlserializer

Please do give those a read and if you still feel this is something that can be solved with ExtendedXmlSerializer I can try to help further assist you.  I may need more code/reference to do so, however. :)

**Comment by Mike-E-angelo** [comment]
Going through older questions and it appears this one has been answered.  Please do let me know if you have any further comments/questions and I will further assist you. 👍
