### ISSUE TITLE
Dictionary/List serialization issue/question

### ISSUE THREAD

**Issue by c0deExplorer** [ExtendedXmlSerializer/home#604]
I would like to reach out for your guidance for couple of questions I have with Dictionary/List serialization.

Here's a sample XML serialized out of ExtendedXmlSerializer:
https://codebeautify.org/alleditor/y231598d5

And heres the object:
`var xmlTestingObject = new List<Subject>
{ 
    new Subject
    {
        Count = 1,
        Message = "Message1",
        Destinations = new Dictionary<string, TestType>
        {
            {"Dest1", new TestType{ ABC = "abc1", DEF="def2"} },
            {"Dest11", new TestType{ ABC = "abc11", DEF="def22"} }
        }
    },
    new Subject
    {
        Count = 2,
        Message = "Message2",
        Destinations = new Dictionary<string, TestType>
        {
            {"Dest2", new TestType{ ABC = "abc21", DEF="def22"} },
            {"Dest22", new TestType{ ABC = "abc21", DEF="def22"} }
        }
    }
};
`

1) How do I get rid of :
`<List
	xmlns:exs="https://extendedxmlserializer.github.io/v2" exs:arguments="Subject">
	<Capacity>4</Capacity>`

2) How do I change the element name of "item" in a dictionary (also , is it possible to change the element name for "key" and "value" for a dictionary serialization.

Thanks and appreciate your inputs.

**Comment by Mike-E-angelo** [comment]
Hi @c0deExplorer thank you for writing in.  For my edification can you provide the container configuration code you used to generate the XML in question?  This will assist me in knowing how to proceed.

**Comment by c0deExplorer** [comment]
Thanks much @Mike-E-angelo . Here's the config I am trying out as of now:
`        IExtendedXmlSerializer serializerTest = new ConfigurationContainer()
                                                  .EnableImplicitTyping(typeof(Dictionary<string, TestType>),
                                                                        typeof(List<Subject>), typeof(Subject))
                                            
                                                  .Create();`

**Comment by Mike-E-angelo** [comment]
Alright @c0deExplorer it took some time here to brush off the dust but I am happy to say that what you are after is possible.  Please check out this test/configuration:

https://github.com/ExtendedXmlSerializer/home/blob/a4f8a3509ed246bac0ab37c54ecc9e357055d14a/test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue604Tests.cs

You will find that it emits the following:

```
<?xml version="1.0" encoding="utf-8"?>
<Issue604Tests-Subject>
	<Store>
		<Entry>
			<Key>Hello</Key>
			<Value>true</Value>
		</Entry>
		<Entry>
			<Key>World</Key>
			<Value>false</Value>
		</Entry>
	</Store>
</Issue604Tests-Subject>
```

So the extra attributes are removed and `Item` has been renamed to `Entry`.

Please let me know if you have any further questions and I will assist,

**Comment by c0deExplorer** [comment]
Thank you so much @Mike-E-angelo. Never knew about _InspectedPropertyTypes_.  It did do the trick!! Great work! I'll work on it and get back if I see anything different.  Again, Thanks a ton for your wonderful support and really appreciate your time spend to investigate this.

**Comment by Mike-E-angelo** [comment]
Thank you for the kind words.  If you ever need any further assistance please open a new issue and we will take a look into it.  Closing this for now.
