### ISSUE TITLE
ShouldSerialize is not working.

### ISSUE THREAD

**Issue by egalambos** [ExtendedXmlSerializer/home#607]
I have what's below and ShouldSerializeDefault is never called.  Might this be because XmlElement has been defined??

        [XmlElement("DEFAULT_PRICING_DATA")]
        [JsonProperty(PropertyName="DEFAULT_PRICING_DATA")]
        public PricingData Default { get; set; }

        [XmlIgnore]
        public bool SaveDefaultValues { get; set; }

        public bool ShouldSerializeDefault()
        {
            return SaveDefaultValues;
        }

**Comment by Mike-E-angelo** [comment]
Hey there @egalambos thank you for your question and for writing in.  We use a different approach from the classical serializer.  You can find some examples here:
https://github.com/ExtendedXmlSerializer/home/blob/4ab31a26cfa72fe4d27ee8de3b00f0366aea73b0/test/ExtendedXmlSerializer.Tests.ReportedIssues/Issue530Tests.cs#L34

Please let me know if you have any further questions; I will do my best to assist you.

**Comment by Mike-E-angelo** [comment]
Sounds like this issue was answered.  If not please leave a comment and I will re-open.  Closing this issue for now.
