### ISSUE TITLE
Question: When Deserializing whats the best way to pass data to sub objects

### ISSUE THREAD

**Issue by push-22** [ExtendedXmlSerializer/home#631]
I have xml like this:
```
<Envelope version="1.2">
    <SubObject>
        <Name>bert</Name>
    </SubObject>
</Envelope>

```
And I'd like to deserialize SubObject to a class like this:
```
class SubObject {
  public string Name {get; set;}
  public float Version {get; set;}
}
```
Is there any way of getting the version attribute of the Envelope tag , set into SubObject?

I'm currently reading the xml like as below so I could pass it into an instance of SubObject via a constructor, however there doesn't appear to be a version of deserialize that just take the XmlReader _and_ an instance of the object.

```
using var body = Request.BodyReader.AsStream();
XmlReaderSettings settings = new XmlReaderSettings { ... };
using (XmlReader reader = XmlReader.Create(body, settings)) {
    reader.MoveToContent();
float version = 1.3F;
do {
    if (reader.NodeType == XmlNodeType.Element) {
        string name = reader.Name;
        switch (name) {
            case "Envelope":
                if (reader.MoveToFirstAttribute()) {
                    do {
                        switch (reader.Name) {
                            case "version":
                                float.TryParse(reader.Value, out version); 
                                break;
                        }
                    } while (reader.MoveToNextAttribute());
                }
                break;
            case "SubObject":
                IExtendedXmlSerializer serializer = new ConfigurationContainer()
                                .UseOptimizedNamespaces()
                                .EnableImplicitTyping(typeof(SubObject))
                                .Create();
               var newInstance = new SubObject(version);
               // how do I put newInstance into Deserialize, reset the stream?
               var post = serializer.Deserialize(reader) as SubObject;
                if (post is not null) {
                    return Ok(post.Response);
                }
                break;
```
Or I could do it one go like:
```
class SubObject {
  public SubObject(float version or. Envelope parent) {....}
...
}

 class Envelope {
      public float Version {get; set;} = 0;
      public SubObject SubObject {get; set;} 
 }

// create reader from stream etc...
IExtendedXmlSerializer serializer = new ConfigurationContainer()
                                    .UseOptimizedNamespaces()
                                    .EnableImplicitTyping(typeof(Envelope))
                                    .Create(); 

 // But how'd I get the parent data into the subobject? 

```

Many Thanks.

**Comment by Mike-E-angelo** [comment]
Hey @push-22 thank you for the question.  The reading half of the deserializer suffers from some quirks so I try to stay away from it if possible.  One possibility is to use a serialization monitor:

```
	public sealed class Issue630Tests
	{
		[Fact]
		public void VerifyPassThroughValue()
		{
			var sut = new ConfigurationContainer().Type<Envelope>().WithMonitor(Monitor.Default).Create().ForTesting();

			var instance = new Envelope { Version = 1.2f, SubObject = new() };
			sut.Cycle(instance).SubObject.Version.Should().Be(1.2f);
		}

		sealed class Monitor : ISerializationMonitor<Envelope>
		{
			public static Monitor Default { get; } = new();

			Monitor() {}

			public void OnSerializing(IFormatWriter writer, Envelope instance) {}

			public void OnSerialized(IFormatWriter writer, Envelope instance) {}

			public void OnDeserializing(IFormatReader reader, Type instanceType) {}

			public void OnActivating(IFormatReader reader, Type instanceType) {}

			public void OnActivated(Envelope instance) {}

			public void OnDeserialized(IFormatReader reader, Envelope instance)
			{
				instance.SubObject.Version = instance.Version;
			}
		}

		sealed class Envelope
		{
			public float Version {get; set;}
			public SubObject SubObject { get; set; }
		}
		sealed class SubObject {
			public string Name {get; set;}
			public float Version {get; set;}
		}
	}
```

If that doesn't work for your purposes I can see about getting that reader available for you. 👍

**Comment by push-22** [comment]
I've been playing with this, but it doesn't easily fit, I didn't say, but the Envelope can can contain one of many different types of SubObject, which may or may not be there on deserialization. Thats why we're using the switch to "get to" that first object then creating it from there and why I liked the idea of being able to set the version in the SubObjects constructor before deserializing it.

How easy would it be to pipe through the existing XmlReader?

**Comment by push-22** [comment]
This HACK appears to work ok in my code: (from ReferencedDeserializationContext.cs)
```
        public T Deserialize(System.Xml.XmlReader reader)
        {
            var existing = new Existing(reader, _existing);
            var result = (T)_reader.Get(existing);
            return result;
        }
```

Obviously, I've not tested this beyond running your original tests

**Comment by Mike-E-angelo** [comment]
Ah you beat me to the punch there @push-22 I just started looking into this now. 😁  Adding a new overload for an `XmlReader` is exactly what I was thinking of doing.  If I add a new method would that get you situated here?

**Comment by push-22** [comment]
Actually testing it more, It doesn't work. the patch seems to return a new object who version is set to 0 - sorry.

**Comment by Mike-E-angelo** [comment]
Doh, well you get the overload anyways @push-22 😃  I am unclear how to assist here as the goal of EXS was/is to serialize .NET object graphs and there isn't a lot of emphasis placed on classic XmlReader/XmlWriter.  We're also facing the fact that I haven't really been involved in this codebase for several years now, so it's a bit of a challenge personally to assist in this area.  If you have any further developments I will be more than happy to see if I can further assist you, however. 👍

**Comment by push-22** [comment]
Thanks

**Comment by Mike-E-angelo** [comment]
Oh, another consideration... maybe use XSLT to copy that value and then apply it to the child nodes as necessary? 🤔

**Comment by push-22** [comment]
That would be way too slow i'm afraid  - I don't really understand why its coming back with a copy and not the actual instance. But if thats the way it works thats it I guess.

Many thanks.

**Comment by Mike-E-angelo** [comment]
> But if thats the way it works thats it I guess.

TBH it's a little unclear to me the problem at the moment.  If you can write me a unit test that shows the problem from front to back I can take a look into it for you. 👍
